"""
DayTraders Miracle_CURSOR - Database Manager (v1)
==================================================
Generated by: Cursor AI Agent (cursor-generated)
Date: 2026-02-09

Manages SQLite database with tables following the "1" naming convention.
Compatible with the STOCKSUNIFY2 ecosystem.
"""

import sqlite3
import os
import json
import hashlib
from datetime import datetime
from pathlib import Path

DB_DIR = Path(__file__).parent
DB_PATH = DB_DIR / "miracle_cursor_1.db"
SCHEMA_PATH = DB_DIR / "schema_1.sql"


class MiracleCursorDB:
    """Database manager for the DayTraders Miracle_CURSOR tool."""
    
    def __init__(self, db_path: str = None):
        self.db_path = db_path or str(DB_PATH)
        self._ensure_db()
    
    def _ensure_db(self):
        """Initialize database with schema if it doesn't exist."""
        is_new = not os.path.exists(self.db_path)
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        
        if is_new or self._is_empty(conn):
            schema_sql = SCHEMA_PATH.read_text()
            conn.executescript(schema_sql)
            conn.commit()
            print(f"[DB] Initialized database at {self.db_path}")
        
        conn.close()
    
    def _is_empty(self, conn):
        """Check if db has no tables."""
        cur = conn.execute("SELECT count(*) FROM sqlite_master WHERE type='table'")
        return cur.fetchone()[0] == 0
    
    def _connect(self):
        """Get a database connection."""
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        return conn
    
    # ---- Strategies ----
    
    def get_strategies(self, active_only=True):
        """Get all strategies."""
        conn = self._connect()
        q = "SELECT * FROM strategies_1"
        if active_only:
            q += " WHERE is_active = 1"
        rows = conn.execute(q).fetchall()
        conn.close()
        return [dict(r) for r in rows]
    
    def get_strategy(self, strategy_id: int):
        """Get a single strategy by ID."""
        conn = self._connect()
        row = conn.execute("SELECT * FROM strategies_1 WHERE strategy_id = ?", (strategy_id,)).fetchone()
        conn.close()
        return dict(row) if row else None
    
    def get_strategy_by_name(self, name: str):
        """Get a single strategy by name."""
        conn = self._connect()
        row = conn.execute("SELECT * FROM strategies_1 WHERE strategy_name = ?", (name,)).fetchone()
        conn.close()
        return dict(row) if row else None
    
    # ---- Portfolios ----
    
    def get_portfolios(self, active_only=True):
        """Get all portfolios."""
        conn = self._connect()
        q = "SELECT * FROM portfolios_1"
        if active_only:
            q += " WHERE is_active = 1"
        rows = conn.execute(q).fetchall()
        conn.close()
        return [dict(r) for r in rows]
    
    # ---- Trading Signals ----
    
    def insert_signal(self, signal: dict) -> int:
        """Insert a trading signal and return its ID."""
        # Generate pick hash for audit trail
        hash_input = f"{signal['symbol']}|{signal['current_price']}|{signal['entry_price']}|{signal.get('picked_at', datetime.utcnow().isoformat())}"
        signal['pick_hash'] = hashlib.sha256(hash_input.encode()).hexdigest()
        
        conn = self._connect()
        cols = [k for k in signal.keys() if k != 'signal_id']
        placeholders = ', '.join(['?' for _ in cols])
        col_names = ', '.join(cols)
        values = [signal[c] for c in cols]
        
        cur = conn.execute(
            f"INSERT INTO trading_signals_1 ({col_names}) VALUES ({placeholders})",
            values
        )
        signal_id = cur.lastrowid
        conn.commit()
        conn.close()
        return signal_id
    
    def insert_score_breakdown(self, signal_id: int, breakdowns: list):
        """Insert score breakdown components for a signal."""
        conn = self._connect()
        for b in breakdowns:
            conn.execute(
                "INSERT INTO signal_scores_breakdown_1 (signal_id, component_name, component_score, max_score, weight, notes) VALUES (?, ?, ?, ?, ?, ?)",
                (signal_id, b['component_name'], b['component_score'], b['max_score'], b.get('weight', 1.0), b.get('notes', ''))
            )
        conn.commit()
        conn.close()
    
    def get_active_signals(self, strategy_id: int = None):
        """Get active trading signals, optionally filtered by strategy."""
        conn = self._connect()
        q = "SELECT * FROM trading_signals_1 WHERE status = 'active'"
        params = []
        if strategy_id:
            q += " AND strategy_id = ?"
            params.append(strategy_id)
        q += " ORDER BY score DESC"
        rows = conn.execute(q, params).fetchall()
        conn.close()
        return [dict(r) for r in rows]
    
    def get_signals_by_date(self, date_str: str):
        """Get all signals generated on a specific date."""
        conn = self._connect()
        rows = conn.execute(
            "SELECT * FROM trading_signals_1 WHERE date(picked_at) = ? ORDER BY score DESC",
            (date_str,)
        ).fetchall()
        conn.close()
        return [dict(r) for r in rows]
    
    def close_signal(self, signal_id: int, exit_price: float, reason: str):
        """Close a signal with actual exit price and reason."""
        conn = self._connect()
        signal = conn.execute("SELECT * FROM trading_signals_1 WHERE signal_id = ?", (signal_id,)).fetchone()
        if signal:
            entry = signal['entry_price']
            pnl = exit_price - entry if signal['signal_type'] == 'LONG' else entry - exit_price
            conn.execute(
                "UPDATE trading_signals_1 SET status = 'closed', actual_exit = ?, actual_pnl = ?, exit_reason = ?, closed_at = ? WHERE signal_id = ?",
                (exit_price, pnl, reason, datetime.utcnow().isoformat(), signal_id)
            )
            conn.commit()
        conn.close()
    
    # ---- Scan Results ----
    
    def insert_scan_result(self, scan_date: str, symbol: str, strategy_name: str, raw_score: float, passed: bool, data_json: str = None):
        """Insert a daily scan result."""
        conn = self._connect()
        conn.execute(
            "INSERT INTO daily_scan_results_1 (scan_date, symbol, strategy_name, raw_score, passed_filter, scan_data_json) VALUES (?, ?, ?, ?, ?, ?)",
            (scan_date, symbol, strategy_name, raw_score, 1 if passed else 0, data_json)
        )
        conn.commit()
        conn.close()
    
    # ---- CDR Registry ----
    
    def get_cdr_for_symbol(self, us_symbol: str):
        """Check if a CDR exists for a US symbol."""
        conn = self._connect()
        row = conn.execute(
            "SELECT * FROM cdr_registry_1 WHERE us_symbol = ? AND is_active = 1",
            (us_symbol.upper(),)
        ).fetchone()
        conn.close()
        return dict(row) if row else None
    
    def get_all_cdrs(self):
        """Get all active CDRs."""
        conn = self._connect()
        rows = conn.execute("SELECT * FROM cdr_registry_1 WHERE is_active = 1").fetchall()
        conn.close()
        return [dict(r) for r in rows]
    
    # ---- Fee Model ----
    
    def get_fee_model(self):
        """Get the Questrade fee model."""
        conn = self._connect()
        rows = conn.execute("SELECT * FROM questrade_fee_model_1").fetchall()
        conn.close()
        return [dict(r) for r in rows]
    
    # ---- Performance ----
    
    def log_performance(self, date_str: str, strategy_id: int, portfolio_id: int, stats: dict):
        """Log daily performance stats."""
        conn = self._connect()
        conn.execute(
            "INSERT INTO performance_log_1 (date, strategy_id, portfolio_id, total_signals, wins, losses, win_rate, total_pnl, avg_return_pct, max_drawdown_pct, sharpe_ratio, notes) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            (date_str, strategy_id, portfolio_id,
             stats.get('total_signals', 0), stats.get('wins', 0), stats.get('losses', 0),
             stats.get('win_rate', 0), stats.get('total_pnl', 0), stats.get('avg_return_pct', 0),
             stats.get('max_drawdown_pct', 0), stats.get('sharpe_ratio', None), stats.get('notes', ''))
        )
        conn.commit()
        conn.close()
    
    # ---- Export ----
    
    def export_signals_json(self, output_path: str = None):
        """Export all active signals as JSON (compatible with daily-stocks.json format)."""
        signals = self.get_active_signals()
        
        export = {
            "tool": "DayTraders Miracle_CURSOR",
            "generated_by": "cursor_ai_agent",
            "lastUpdated": datetime.utcnow().isoformat() + "Z",
            "totalPicks": len(signals),
            "stocks": []
        }
        
        for s in signals:
            export["stocks"].append({
                "symbol": s["symbol"],
                "name": s.get("company_name", ""),
                "price": s["current_price"],
                "entryPrice": s["entry_price"],
                "stopLoss": s["stop_loss"],
                "takeProfit1": s["take_profit_1"],
                "takeProfit2": s.get("take_profit_2"),
                "takeProfit3": s.get("take_profit_3"),
                "rating": s["rating"],
                "score": s["score"],
                "risk": s.get("confidence", "medium"),
                "timeframe": s["timeframe"],
                "strategy": s.get("strategy_id"),
                "riskRewardRatio": s["risk_reward_ratio"],
                "commissionCost": s["commission_cost"],
                "fxFeeCost": s["fx_fee_cost"],
                "netProfitTarget": s["net_profit_target"],
                "usesCDR": bool(s.get("uses_cdr_savings")),
                "cdrSymbol": s.get("cdr_symbol"),
                "catalyst": s.get("catalyst", ""),
                "indicators": {
                    "rsi": s.get("rsi_14"),
                    "volumeSurge": s.get("volume_surge"),
                    "atr": s.get("atr_14"),
                    "macd": s.get("macd_signal"),
                    "bollinger": s.get("bollinger_pos"),
                },
                "pickedAt": s["picked_at"],
                "pickHash": s.get("pick_hash", ""),
            })
        
        if output_path:
            Path(output_path).parent.mkdir(parents=True, exist_ok=True)
            with open(output_path, 'w') as f:
                json.dump(export, f, indent=2)
            print(f"[DB] Exported {len(signals)} signals to {output_path}")
        
        return export


if __name__ == "__main__":
    db = MiracleCursorDB()
    print("Strategies:", json.dumps(db.get_strategies(), indent=2, default=str))
    print("Portfolios:", json.dumps(db.get_portfolios(), indent=2, default=str))
    print("CDRs:", len(db.get_all_cdrs()))
    print("Fee Model:", json.dumps(db.get_fee_model(), indent=2, default=str))
