-- =============================================================================
-- DayTraders Miracle_CURSOR - Database Schema v1
-- Generated by: Cursor AI Agent (cursor-generated)
-- Date: 2026-02-09
-- 
-- NOTE: All tables include "1" in their names per project naming convention.
-- This schema is compatible with SQLite (local) and MySQL/Postgres (production).
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Table: strategies_1
-- Stores available trading strategy definitions
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS strategies_1 (
    strategy_id     INTEGER PRIMARY KEY AUTOINCREMENT,
    strategy_name   TEXT NOT NULL UNIQUE,
    strategy_type   TEXT NOT NULL DEFAULT 'day_trade',  -- day_trade | swing | scalp | momentum_burst
    description     TEXT,
    risk_level      TEXT NOT NULL DEFAULT 'medium',     -- low | medium | high | very_high
    timeframe       TEXT NOT NULL DEFAULT '1d',         -- 1h | 4h | 1d | 3d | 7d
    min_score       REAL NOT NULL DEFAULT 70.0,
    max_positions   INTEGER NOT NULL DEFAULT 5,
    default_stop_loss_pct   REAL NOT NULL DEFAULT 3.0,  -- percentage below entry
    default_take_profit_pct REAL NOT NULL DEFAULT 6.0,  -- percentage above entry
    commission_model TEXT NOT NULL DEFAULT 'questrade', -- questrade | ibkr | free
    prefer_cdr      INTEGER NOT NULL DEFAULT 1,         -- 1 = prefer CDRs when available
    is_active       INTEGER NOT NULL DEFAULT 1,
    created_at      TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at      TEXT NOT NULL DEFAULT (datetime('now')),
    generated_by    TEXT NOT NULL DEFAULT 'cursor_ai_agent'
);

-- ---------------------------------------------------------------------------
-- Table: portfolios_1
-- Stores portfolio configurations for each strategy
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS portfolios_1 (
    portfolio_id    INTEGER PRIMARY KEY AUTOINCREMENT,
    portfolio_name  TEXT NOT NULL UNIQUE,
    strategy_id     INTEGER NOT NULL,
    initial_capital REAL NOT NULL DEFAULT 10000.0,
    current_capital REAL NOT NULL DEFAULT 10000.0,
    currency        TEXT NOT NULL DEFAULT 'CAD',        -- CAD | USD
    max_risk_per_trade_pct  REAL NOT NULL DEFAULT 2.0,  -- max % of capital per trade
    max_daily_loss_pct      REAL NOT NULL DEFAULT 5.0,  -- max % daily drawdown
    is_paper_trading        INTEGER NOT NULL DEFAULT 1, -- 1 = paper trading mode
    broker          TEXT NOT NULL DEFAULT 'questrade',
    account_type    TEXT NOT NULL DEFAULT 'tfsa',       -- tfsa | rrsp | margin | cash
    is_active       INTEGER NOT NULL DEFAULT 1,
    created_at      TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at      TEXT NOT NULL DEFAULT (datetime('now')),
    generated_by    TEXT NOT NULL DEFAULT 'cursor_ai_agent',
    FOREIGN KEY (strategy_id) REFERENCES strategies_1(strategy_id)
);

-- ---------------------------------------------------------------------------
-- Table: trading_signals_1
-- Stores generated trade signals / picks from the Miracle engine
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS trading_signals_1 (
    signal_id       INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol          TEXT NOT NULL,
    company_name    TEXT,
    exchange        TEXT,                               -- NYSE | NASDAQ | TSX | NEO
    is_cdr          INTEGER NOT NULL DEFAULT 0,         -- 1 = Canadian Depositary Receipt
    cdr_symbol      TEXT,                               -- e.g., AAPL.NE for Apple CDR
    strategy_id     INTEGER NOT NULL,
    signal_type     TEXT NOT NULL DEFAULT 'LONG',       -- LONG | SHORT
    rating          TEXT NOT NULL DEFAULT 'BUY',        -- STRONG_BUY | BUY | HOLD | SELL
    score           REAL NOT NULL DEFAULT 0.0,          -- 0-100 composite score
    
    -- Price levels
    current_price   REAL NOT NULL,
    entry_price     REAL NOT NULL,                      -- recommended entry (with slippage)
    stop_loss       REAL NOT NULL,
    take_profit_1   REAL NOT NULL,                      -- conservative TP
    take_profit_2   REAL,                               -- aggressive TP
    take_profit_3   REAL,                               -- moonshot TP
    
    -- Risk/Reward
    risk_reward_ratio   REAL NOT NULL DEFAULT 0.0,
    position_size_pct   REAL NOT NULL DEFAULT 0.0,      -- % of portfolio
    estimated_risk_usd  REAL NOT NULL DEFAULT 0.0,
    estimated_reward_usd REAL NOT NULL DEFAULT 0.0,
    
    -- Fee calculation
    commission_cost     REAL NOT NULL DEFAULT 0.0,      -- estimated total commission (buy + sell)
    fx_fee_cost         REAL NOT NULL DEFAULT 0.0,      -- estimated FX conversion fee
    net_profit_target   REAL NOT NULL DEFAULT 0.0,      -- profit after fees at TP1
    uses_cdr_savings    INTEGER NOT NULL DEFAULT 0,     -- 1 = saved money via CDR
    
    -- Technical indicators
    rsi_14          REAL,
    volume_surge    REAL,                               -- current vol / avg vol
    atr_14          REAL,                               -- Average True Range
    sma_20          REAL,
    sma_50          REAL,
    sma_200         REAL,
    macd_signal     TEXT,                               -- bullish | bearish | neutral
    bollinger_pos   TEXT,                               -- upper | middle | lower | squeeze
    vwap            REAL,
    
    -- Catalyst / reason
    catalyst        TEXT,                               -- why this pick is expected to move
    confidence      TEXT NOT NULL DEFAULT 'medium',     -- low | medium | high | very_high
    timeframe       TEXT NOT NULL DEFAULT '1d',
    expiry          TEXT,                               -- signal expiry datetime
    
    -- Tracking
    status          TEXT NOT NULL DEFAULT 'active',     -- active | triggered | stopped | expired | closed
    actual_entry    REAL,
    actual_exit     REAL,
    actual_pnl      REAL,
    exit_reason     TEXT,                               -- tp_hit | sl_hit | manual | expired
    
    picked_at       TEXT NOT NULL DEFAULT (datetime('now')),
    closed_at       TEXT,
    pick_hash       TEXT,                               -- immutable hash for audit trail
    
    generated_by    TEXT NOT NULL DEFAULT 'cursor_ai_agent',
    FOREIGN KEY (strategy_id) REFERENCES strategies_1(strategy_id)
);

-- ---------------------------------------------------------------------------
-- Table: signal_scores_breakdown_1
-- Detailed score breakdown for each signal
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS signal_scores_breakdown_1 (
    breakdown_id    INTEGER PRIMARY KEY AUTOINCREMENT,
    signal_id       INTEGER NOT NULL,
    component_name  TEXT NOT NULL,          -- e.g. 'momentum', 'volume', 'trend', 'catalyst'
    component_score REAL NOT NULL DEFAULT 0.0,
    max_score       REAL NOT NULL DEFAULT 0.0,
    weight          REAL NOT NULL DEFAULT 1.0,
    notes           TEXT,
    FOREIGN KEY (signal_id) REFERENCES trading_signals_1(signal_id)
);

-- ---------------------------------------------------------------------------
-- Table: daily_scan_results_1
-- Raw scan results before filtering into signals
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS daily_scan_results_1 (
    scan_id         INTEGER PRIMARY KEY AUTOINCREMENT,
    scan_date       TEXT NOT NULL,
    symbol          TEXT NOT NULL,
    strategy_name   TEXT NOT NULL,
    raw_score       REAL NOT NULL DEFAULT 0.0,
    passed_filter   INTEGER NOT NULL DEFAULT 0,
    scan_data_json  TEXT,                   -- full indicator snapshot as JSON
    scanned_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

-- ---------------------------------------------------------------------------
-- Table: performance_log_1
-- Historical performance tracking for strategy validation
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS performance_log_1 (
    log_id          INTEGER PRIMARY KEY AUTOINCREMENT,
    date            TEXT NOT NULL,
    strategy_id     INTEGER NOT NULL,
    portfolio_id    INTEGER,
    total_signals   INTEGER NOT NULL DEFAULT 0,
    wins            INTEGER NOT NULL DEFAULT 0,
    losses          INTEGER NOT NULL DEFAULT 0,
    win_rate        REAL NOT NULL DEFAULT 0.0,
    total_pnl       REAL NOT NULL DEFAULT 0.0,
    avg_return_pct  REAL NOT NULL DEFAULT 0.0,
    max_drawdown_pct REAL NOT NULL DEFAULT 0.0,
    sharpe_ratio    REAL,
    notes           TEXT,
    generated_by    TEXT NOT NULL DEFAULT 'cursor_ai_agent',
    FOREIGN KEY (strategy_id) REFERENCES strategies_1(strategy_id),
    FOREIGN KEY (portfolio_id) REFERENCES portfolios_1(portfolio_id)
);

-- ---------------------------------------------------------------------------
-- Table: cdr_registry_1
-- Registry of known CDRs (Canadian Depositary Receipts) for fee optimization
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS cdr_registry_1 (
    cdr_id          INTEGER PRIMARY KEY AUTOINCREMENT,
    us_symbol       TEXT NOT NULL,          -- e.g. AAPL
    cdr_symbol      TEXT NOT NULL,          -- e.g. AAPL.NE
    company_name    TEXT,
    exchange        TEXT NOT NULL DEFAULT 'NEO',  -- NEO exchange
    currency        TEXT NOT NULL DEFAULT 'CAD',
    fx_hedge        INTEGER NOT NULL DEFAULT 1,   -- 1 = currency hedged
    last_verified   TEXT,
    is_active       INTEGER NOT NULL DEFAULT 1,
    notes           TEXT,
    generated_by    TEXT NOT NULL DEFAULT 'cursor_ai_agent'
);

-- ---------------------------------------------------------------------------
-- Table: questrade_fee_model_1
-- Questrade commission structure for accurate profit calculation
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS questrade_fee_model_1 (
    fee_id          INTEGER PRIMARY KEY AUTOINCREMENT,
    fee_type        TEXT NOT NULL,          -- 'equity_commission' | 'ecn_fee' | 'fx_conversion' | 'etf_buy'
    description     TEXT NOT NULL,
    min_fee         REAL NOT NULL DEFAULT 0.0,
    max_fee         REAL NOT NULL DEFAULT 0.0,
    per_share_fee   REAL NOT NULL DEFAULT 0.0,
    percentage_fee  REAL NOT NULL DEFAULT 0.0,
    applies_to      TEXT NOT NULL DEFAULT 'all',  -- 'all' | 'us_stocks' | 'cad_stocks' | 'etf'
    notes           TEXT,
    last_updated    TEXT NOT NULL DEFAULT (datetime('now')),
    generated_by    TEXT NOT NULL DEFAULT 'cursor_ai_agent'
);

-- ---------------------------------------------------------------------------
-- Insert default strategies
-- ---------------------------------------------------------------------------
INSERT OR IGNORE INTO strategies_1 (strategy_name, strategy_type, description, risk_level, timeframe, min_score, max_positions, default_stop_loss_pct, default_take_profit_pct, commission_model, prefer_cdr) VALUES
('Miracle Momentum Burst', 'momentum_burst', 'High-probability short-term momentum plays. Targets stocks with explosive volume + breakout patterns within 1-3 days. The flagship DayTraders Miracle strategy.', 'high', '1d', 75.0, 3, 2.5, 5.0, 'questrade', 1),
('CDR Advantage Swing', 'swing', 'Swing trades using CDR-listed stocks to eliminate FX fees. 3-7 day holds targeting breakouts on major US names traded via NEO exchange CDRs.', 'medium', '3d', 70.0, 5, 3.0, 8.0, 'questrade', 1),
('Scalp Lightning', 'scalp', 'Ultra-short scalping strategy for liquid large-caps. Sub-1-day holds, tight stops, quick profits. Best for active monitoring.', 'very_high', '1h', 80.0, 2, 1.0, 2.0, 'questrade', 0),
('Penny Rocket', 'day_trade', 'High-risk penny stock plays targeting 10%+ moves on volume spikes. Small position sizes, strict risk management.', 'very_high', '1d', 80.0, 2, 5.0, 15.0, 'questrade', 0),
('Blue Chip Breakout', 'swing', 'Conservative breakout strategy on S&P 500 / TSX 60 components. Lower risk, steady returns, 3-7 day holds.', 'low', '3d', 65.0, 5, 2.0, 5.0, 'questrade', 1),
('Sector Rotation Alpha', 'swing', 'Rotates into the strongest sector ETFs and top holdings. Targets sector momentum shifts over 1-2 weeks.', 'medium', '7d', 70.0, 4, 3.0, 7.0, 'questrade', 1);

-- ---------------------------------------------------------------------------
-- Insert default portfolios
-- ---------------------------------------------------------------------------
INSERT OR IGNORE INTO portfolios_1 (portfolio_name, strategy_id, initial_capital, current_capital, currency, max_risk_per_trade_pct, max_daily_loss_pct, broker, account_type) VALUES
('Miracle Paper Trade', 1, 10000.0, 10000.0, 'CAD', 2.0, 5.0, 'questrade', 'tfsa'),
('CDR Swing Portfolio', 2, 25000.0, 25000.0, 'CAD', 1.5, 3.0, 'questrade', 'tfsa'),
('Scalp Active', 3, 5000.0, 5000.0, 'CAD', 1.0, 3.0, 'questrade', 'margin'),
('Penny Rocket Fund', 4, 2000.0, 2000.0, 'CAD', 3.0, 10.0, 'questrade', 'cash'),
('Blue Chip Steady', 5, 50000.0, 50000.0, 'CAD', 1.0, 2.0, 'questrade', 'rrsp');

-- ---------------------------------------------------------------------------
-- Insert Questrade fee model
-- ---------------------------------------------------------------------------
INSERT OR IGNORE INTO questrade_fee_model_1 (fee_type, description, min_fee, max_fee, per_share_fee, percentage_fee, applies_to, notes) VALUES
('equity_commission', 'Questrade equity commission', 4.95, 9.95, 0.01, 0.0, 'all', 'Min $4.95, max $9.95 per trade. $0.01/share.'),
('ecn_fee', 'ECN/routing fee', 0.0, 0.0, 0.0035, 0.0, 'all', 'ECN fee adds ~$0.0035/share on top of commission.'),
('fx_conversion', 'USD/CAD currency conversion fee', 0.0, 0.0, 0.0, 1.5, 'us_stocks', '1.5% spread on currency conversion. Avoided with CDRs or Norbert Gambit.'),
('etf_buy', 'ETF purchase commission', 0.0, 0.0, 0.0, 0.0, 'etf', 'Free to buy ETFs on Questrade. Selling has normal commission.'),
('etf_sell', 'ETF sell commission', 4.95, 9.95, 0.01, 0.0, 'etf', 'Normal equity commission applies when selling ETFs.');

-- ---------------------------------------------------------------------------
-- Insert known CDRs (Canadian Depositary Receipts on NEO Exchange)
-- ---------------------------------------------------------------------------
INSERT OR IGNORE INTO cdr_registry_1 (us_symbol, cdr_symbol, company_name, exchange, currency, fx_hedge, notes) VALUES
('AAPL', 'AAPL.NE', 'Apple Inc.', 'NEO', 'CAD', 1, 'Currency-hedged CDR on NEO Exchange'),
('MSFT', 'MSFT.NE', 'Microsoft Corporation', 'NEO', 'CAD', 1, 'Currency-hedged CDR on NEO Exchange'),
('GOOGL', 'GOOG.NE', 'Alphabet Inc.', 'NEO', 'CAD', 1, 'Currency-hedged CDR on NEO Exchange'),
('AMZN', 'AMZN.NE', 'Amazon.com Inc.', 'NEO', 'CAD', 1, 'Currency-hedged CDR on NEO Exchange'),
('META', 'META.NE', 'Meta Platforms Inc.', 'NEO', 'CAD', 1, 'Currency-hedged CDR on NEO Exchange'),
('TSLA', 'TSLA.NE', 'Tesla Inc.', 'NEO', 'CAD', 1, 'Currency-hedged CDR on NEO Exchange'),
('NVDA', 'NVDA.NE', 'NVIDIA Corporation', 'NEO', 'CAD', 1, 'Currency-hedged CDR on NEO Exchange'),
('JPM', 'JPM.NE', 'JPMorgan Chase & Co.', 'NEO', 'CAD', 1, 'Currency-hedged CDR on NEO Exchange'),
('V', 'V.NE', 'Visa Inc.', 'NEO', 'CAD', 1, 'Currency-hedged CDR on NEO Exchange'),
('JNJ', 'JNJ.NE', 'Johnson & Johnson', 'NEO', 'CAD', 1, 'Currency-hedged CDR on NEO Exchange'),
('WMT', 'WMT.NE', 'Walmart Inc.', 'NEO', 'CAD', 1, 'Currency-hedged CDR on NEO Exchange'),
('PG', 'PG.NE', 'Procter & Gamble Co.', 'NEO', 'CAD', 1, 'Currency-hedged CDR on NEO Exchange'),
('XOM', 'XOM.NE', 'Exxon Mobil Corporation', 'NEO', 'CAD', 1, 'Currency-hedged CDR on NEO Exchange'),
('UNH', 'UNH.NE', 'UnitedHealth Group Inc.', 'NEO', 'CAD', 1, 'Currency-hedged CDR on NEO Exchange'),
('HD', 'HD.NE', 'Home Depot Inc.', 'NEO', 'CAD', 1, 'Currency-hedged CDR on NEO Exchange'),
('DIS', 'DIS.NE', 'Walt Disney Co.', 'NEO', 'CAD', 1, 'Currency-hedged CDR on NEO Exchange'),
('NFLX', 'NFLX.NE', 'Netflix Inc.', 'NEO', 'CAD', 1, 'Currency-hedged CDR on NEO Exchange'),
('INTC', 'INTC.NE', 'Intel Corporation', 'NEO', 'CAD', 1, 'Currency-hedged CDR on NEO Exchange'),
('AMD', 'AMD.NE', 'Advanced Micro Devices Inc.', 'NEO', 'CAD', 1, 'Currency-hedged CDR on NEO Exchange'),
('PFE', 'PFE.NE', 'Pfizer Inc.', 'NEO', 'CAD', 1, 'Currency-hedged CDR on NEO Exchange'),
('BA', 'BA.NE', 'Boeing Co.', 'NEO', 'CAD', 1, 'Currency-hedged CDR on NEO Exchange'),
('CAT', 'CAT.NE', 'Caterpillar Inc.', 'NEO', 'CAD', 1, 'Currency-hedged CDR on NEO Exchange'),
('GS', 'GS.NE', 'Goldman Sachs Group Inc.', 'NEO', 'CAD', 1, 'Currency-hedged CDR on NEO Exchange'),
('SBUX', 'SBUX.NE', 'Starbucks Corporation', 'NEO', 'CAD', 1, 'Currency-hedged CDR on NEO Exchange'),
('COST', 'COST.NE', 'Costco Wholesale Corp.', 'NEO', 'CAD', 1, 'Currency-hedged CDR on NEO Exchange');

-- =============================================================================
-- ADAPTIVE ORACLE TABLES (Self-Adjusting Learning Algorithm)
-- Generated by: Cursor AI Agent (cursor-generated)
-- These tables power the "sister algorithm" that learns from failures and
-- self-adjusts its scoring weights day by day.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Table: adaptive_weights_1
-- Stores the evolving scoring weights for the Adaptive Oracle algorithm.
-- Each row is a snapshot of the weight vector at a point in time.
-- The Oracle adjusts these weights after every completed trade cycle.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS adaptive_weights_1 (
    weight_id       INTEGER PRIMARY KEY AUTOINCREMENT,
    strategy_id     INTEGER NOT NULL,
    epoch           INTEGER NOT NULL DEFAULT 0,          -- learning epoch counter
    -- Scoring component weights (sum to 1.0)
    w_momentum      REAL NOT NULL DEFAULT 0.20,          -- RSI + price momentum
    w_volume        REAL NOT NULL DEFAULT 0.20,          -- volume surge / profile
    w_trend         REAL NOT NULL DEFAULT 0.15,          -- SMA alignment / stage
    w_volatility    REAL NOT NULL DEFAULT 0.10,          -- ATR / Bollinger regime
    w_catalyst      REAL NOT NULL DEFAULT 0.10,          -- breakout / squeeze / gap
    w_sentiment     REAL NOT NULL DEFAULT 0.05,          -- market sentiment proxy
    w_sector_str    REAL NOT NULL DEFAULT 0.05,          -- sector relative strength
    w_risk_reward   REAL NOT NULL DEFAULT 0.10,          -- R:R quality
    w_fee_efficiency REAL NOT NULL DEFAULT 0.05,         -- CDR / cost efficiency
    -- Meta
    learning_rate   REAL NOT NULL DEFAULT 0.05,          -- how aggressively weights shift
    decay_factor    REAL NOT NULL DEFAULT 0.95,          -- exponential decay on old data
    confidence      REAL NOT NULL DEFAULT 0.5,           -- model confidence (0-1)
    total_trades_seen INTEGER NOT NULL DEFAULT 0,
    total_wins      INTEGER NOT NULL DEFAULT 0,
    total_losses    INTEGER NOT NULL DEFAULT 0,
    win_rate        REAL NOT NULL DEFAULT 0.0,
    avg_pnl         REAL NOT NULL DEFAULT 0.0,
    sharpe_estimate REAL,
    is_active       INTEGER NOT NULL DEFAULT 1,
    created_at      TEXT NOT NULL DEFAULT (datetime('now')),
    notes           TEXT,
    generated_by    TEXT NOT NULL DEFAULT 'cursor_ai_agent',
    FOREIGN KEY (strategy_id) REFERENCES strategies_1(strategy_id)
);

-- ---------------------------------------------------------------------------
-- Table: feedback_loop_1
-- Stores every completed trade outcome and the weight adjustment applied.
-- This is the "memory" of the Oracle: what worked, what didn't, and what
-- changed as a result.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS feedback_loop_1 (
    feedback_id     INTEGER PRIMARY KEY AUTOINCREMENT,
    signal_id       INTEGER NOT NULL,
    strategy_id     INTEGER NOT NULL,
    symbol          TEXT NOT NULL,
    -- Outcome
    outcome         TEXT NOT NULL,                       -- 'win' | 'loss' | 'breakeven'
    entry_price     REAL NOT NULL,
    exit_price      REAL NOT NULL,
    pnl             REAL NOT NULL DEFAULT 0.0,
    pnl_pct         REAL NOT NULL DEFAULT 0.0,
    hold_duration_hours REAL NOT NULL DEFAULT 0.0,
    exit_reason     TEXT,                                -- 'tp_hit' | 'sl_hit' | 'expired' | 'manual'
    -- Score at time of pick
    original_score  REAL NOT NULL DEFAULT 0.0,
    -- Component scores at time of pick (for gradient analysis)
    c_momentum      REAL NOT NULL DEFAULT 0.0,
    c_volume        REAL NOT NULL DEFAULT 0.0,
    c_trend         REAL NOT NULL DEFAULT 0.0,
    c_volatility    REAL NOT NULL DEFAULT 0.0,
    c_catalyst      REAL NOT NULL DEFAULT 0.0,
    c_sentiment     REAL NOT NULL DEFAULT 0.0,
    c_sector_str    REAL NOT NULL DEFAULT 0.0,
    c_risk_reward   REAL NOT NULL DEFAULT 0.0,
    c_fee_efficiency REAL NOT NULL DEFAULT 0.0,
    -- Weight adjustment applied after this outcome
    delta_momentum  REAL NOT NULL DEFAULT 0.0,
    delta_volume    REAL NOT NULL DEFAULT 0.0,
    delta_trend     REAL NOT NULL DEFAULT 0.0,
    delta_volatility REAL NOT NULL DEFAULT 0.0,
    delta_catalyst  REAL NOT NULL DEFAULT 0.0,
    delta_sentiment REAL NOT NULL DEFAULT 0.0,
    delta_sector_str REAL NOT NULL DEFAULT 0.0,
    delta_risk_reward REAL NOT NULL DEFAULT 0.0,
    delta_fee_efficiency REAL NOT NULL DEFAULT 0.0,
    -- Epoch before and after
    epoch_before    INTEGER NOT NULL DEFAULT 0,
    epoch_after     INTEGER NOT NULL DEFAULT 0,
    -- Market context at time of trade
    market_regime   TEXT,                                -- 'bull' | 'bear' | 'sideways' | 'volatile'
    spy_change_pct  REAL,                                -- S&P 500 change during hold
    vix_level       REAL,                                -- VIX at entry
    -- Meta
    analyzed_at     TEXT NOT NULL DEFAULT (datetime('now')),
    generated_by    TEXT NOT NULL DEFAULT 'cursor_ai_agent',
    FOREIGN KEY (signal_id) REFERENCES trading_signals_1(signal_id),
    FOREIGN KEY (strategy_id) REFERENCES strategies_1(strategy_id)
);

-- ---------------------------------------------------------------------------
-- Table: regime_memory_1
-- Stores market regime snapshots so the Oracle adjusts differently in
-- bull vs bear vs sideways markets.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS regime_memory_1 (
    regime_id       INTEGER PRIMARY KEY AUTOINCREMENT,
    date            TEXT NOT NULL,
    spy_price       REAL,
    spy_sma_200     REAL,
    spy_rsi         REAL,
    vix_level       REAL,
    regime          TEXT NOT NULL DEFAULT 'unknown',     -- 'bull' | 'bear' | 'sideways' | 'volatile'
    regime_score    REAL NOT NULL DEFAULT 0.0,           -- 0-100 confidence in regime
    sector_leader   TEXT,                                -- which sector is strongest
    sector_laggard  TEXT,                                -- which sector is weakest
    breadth_pct     REAL,                                -- % of stocks above 200 SMA
    notes           TEXT,
    generated_by    TEXT NOT NULL DEFAULT 'cursor_ai_agent'
);

-- ---------------------------------------------------------------------------
-- Table: oracle_predictions_1
-- The Oracle's own prediction log, separate from raw signals.
-- This tracks the "meta-prediction": how confident the Oracle was and
-- whether its confidence calibration was accurate.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS oracle_predictions_1 (
    prediction_id   INTEGER PRIMARY KEY AUTOINCREMENT,
    signal_id       INTEGER,
    symbol          TEXT NOT NULL,
    predicted_direction TEXT NOT NULL DEFAULT 'up',      -- 'up' | 'down' | 'flat'
    predicted_magnitude_pct REAL NOT NULL DEFAULT 0.0,   -- expected % move
    confidence_score REAL NOT NULL DEFAULT 0.0,          -- 0-100
    timeframe       TEXT NOT NULL DEFAULT '1d',
    -- Actual outcome (filled after close)
    actual_direction TEXT,
    actual_magnitude_pct REAL,
    prediction_error REAL,                               -- |predicted - actual|
    was_correct     INTEGER,                             -- 1 = direction was right
    -- Calibration
    calibration_bucket TEXT,                             -- 'high_conf_win', 'high_conf_loss', etc.
    -- Meta
    predicted_at    TEXT NOT NULL DEFAULT (datetime('now')),
    resolved_at     TEXT,
    generated_by    TEXT NOT NULL DEFAULT 'cursor_ai_agent',
    FOREIGN KEY (signal_id) REFERENCES trading_signals_1(signal_id)
);

-- ---------------------------------------------------------------------------
-- Table: symbol_memory_1
-- Per-symbol historical memory: how well the Oracle has done on each ticker.
-- This allows it to avoid symbols where it consistently fails and favor
-- symbols where its model works well.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS symbol_memory_1 (
    memory_id       INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol          TEXT NOT NULL UNIQUE,
    times_picked    INTEGER NOT NULL DEFAULT 0,
    times_won       INTEGER NOT NULL DEFAULT 0,
    times_lost      INTEGER NOT NULL DEFAULT 0,
    win_rate        REAL NOT NULL DEFAULT 0.0,
    avg_pnl_pct     REAL NOT NULL DEFAULT 0.0,
    best_pnl_pct    REAL NOT NULL DEFAULT 0.0,
    worst_pnl_pct   REAL NOT NULL DEFAULT 0.0,
    avg_hold_hours  REAL NOT NULL DEFAULT 0.0,
    -- Which strategies work best for this symbol
    best_strategy_id INTEGER,
    worst_strategy_id INTEGER,
    -- Reliability score: higher = Oracle trusts its read on this symbol more
    reliability_score REAL NOT NULL DEFAULT 50.0,        -- 0-100
    -- Blacklist
    is_blacklisted  INTEGER NOT NULL DEFAULT 0,          -- 1 = Oracle avoids this symbol
    blacklist_reason TEXT,
    last_picked     TEXT,
    last_updated    TEXT NOT NULL DEFAULT (datetime('now')),
    generated_by    TEXT NOT NULL DEFAULT 'cursor_ai_agent'
);

-- ---------------------------------------------------------------------------
-- Insert default Adaptive Oracle strategy
-- ---------------------------------------------------------------------------
INSERT OR IGNORE INTO strategies_1 (strategy_name, strategy_type, description, risk_level, timeframe, min_score, max_positions, default_stop_loss_pct, default_take_profit_pct, commission_model, prefer_cdr) VALUES
('Adaptive Oracle', 'day_trade', 'Self-adjusting algorithm that learns from every trade outcome. Adjusts scoring weights using gradient-like feedback after wins and losses. Becomes more accurate over time by reinforcing what works and penalizing what fails. The sister algorithm to Miracle Momentum Burst.', 'medium', '1d', 72.0, 4, 2.5, 5.5, 'questrade', 1);

-- Insert default adaptive weights for Oracle (strategy_id=7 assuming 6 previous strategies)
INSERT OR IGNORE INTO adaptive_weights_1 (strategy_id, epoch, w_momentum, w_volume, w_trend, w_volatility, w_catalyst, w_sentiment, w_sector_str, w_risk_reward, w_fee_efficiency, learning_rate, decay_factor, confidence) VALUES
(7, 0, 0.20, 0.20, 0.15, 0.10, 0.10, 0.05, 0.05, 0.10, 0.05, 0.05, 0.95, 0.5);

-- Insert Oracle portfolio
INSERT OR IGNORE INTO portfolios_1 (portfolio_name, strategy_id, initial_capital, current_capital, currency, max_risk_per_trade_pct, max_daily_loss_pct, broker, account_type) VALUES
('Adaptive Oracle Paper', 7, 10000.0, 10000.0, 'CAD', 2.0, 4.0, 'questrade', 'tfsa');

-- ---------------------------------------------------------------------------
-- Indexes for adaptive learning tables
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_adaptive_w1_strategy ON adaptive_weights_1(strategy_id);
CREATE INDEX IF NOT EXISTS idx_adaptive_w1_active ON adaptive_weights_1(is_active);
CREATE INDEX IF NOT EXISTS idx_feedback1_signal ON feedback_loop_1(signal_id);
CREATE INDEX IF NOT EXISTS idx_feedback1_outcome ON feedback_loop_1(outcome);
CREATE INDEX IF NOT EXISTS idx_feedback1_strategy ON feedback_loop_1(strategy_id);
CREATE INDEX IF NOT EXISTS idx_regime1_date ON regime_memory_1(date);
CREATE INDEX IF NOT EXISTS idx_oracle_pred1_symbol ON oracle_predictions_1(symbol);
CREATE INDEX IF NOT EXISTS idx_symbol_mem1_symbol ON symbol_memory_1(symbol);
CREATE INDEX IF NOT EXISTS idx_symbol_mem1_reliability ON symbol_memory_1(reliability_score);

-- ---------------------------------------------------------------------------
-- Indexes for performance (original tables)
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_signals1_symbol ON trading_signals_1(symbol);
CREATE INDEX IF NOT EXISTS idx_signals1_status ON trading_signals_1(status);
CREATE INDEX IF NOT EXISTS idx_signals1_strategy ON trading_signals_1(strategy_id);
CREATE INDEX IF NOT EXISTS idx_signals1_picked ON trading_signals_1(picked_at);
CREATE INDEX IF NOT EXISTS idx_signals1_rating ON trading_signals_1(rating);
CREATE INDEX IF NOT EXISTS idx_scan1_date ON daily_scan_results_1(scan_date);
CREATE INDEX IF NOT EXISTS idx_perf1_date ON performance_log_1(date);
CREATE INDEX IF NOT EXISTS idx_cdr1_us ON cdr_registry_1(us_symbol);
