"""
DayTraders Miracle_CURSOR - Core Scanning Engine
==================================================
Generated by: Cursor AI Agent (cursor-generated)
Date: 2026-02-09

The main engine that:
1. Fetches real-time stock data via yfinance
2. Computes technical indicators (RSI, SMAs, ATR, Bollinger, VWAP, MACD)
3. Scores stocks across multiple strategy dimensions
4. Calculates Questrade-aware stop-loss / take-profit / fees
5. Outputs ranked signals with full audit trail

Compatible with the STOCKSUNIFY2 ecosystem.
"""

import json
import math
import hashlib
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional

import numpy as np

try:
    import yfinance as yf
except ImportError:
    yf = None
    print("[WARN] yfinance not installed. Install with: pip install yfinance")

try:
    import pandas as pd
except ImportError:
    pd = None
    print("[WARN] pandas not installed. Install with: pip install pandas")

from questrade_fees import QuestradeFeeCaclulator
from db.database_1 import MiracleCursorDB


# ─────────────────────────────────────────────────────────────────────────────
# STOCK UNIVERSE — Tickers scanned by default
# ─────────────────────────────────────────────────────────────────────────────

UNIVERSE_LARGE_CAP = [
    "AAPL", "MSFT", "GOOGL", "AMZN", "META", "TSLA", "NVDA", "JPM", "V",
    "JNJ", "WMT", "PG", "XOM", "UNH", "HD", "DIS", "NFLX", "INTC", "AMD",
    "PFE", "BA", "CAT", "GS", "SBUX", "COST", "CRM", "ADBE", "PYPL",
    "QCOM", "TXN", "AVGO", "MU", "SNOW", "PLTR",
]

UNIVERSE_MID_CAP = [
    "GM", "F", "RCL", "LUV", "AA", "EOG", "CVX", "SLB", "HUT",
    "STX", "WDC", "SNAP", "PINS", "ROKU", "DKNG", "SOFI",
]

UNIVERSE_PENNY_HIGH_VOL = [
    "PLUG", "FCEL", "CLSK", "MARA", "RIOT", "BBIG", "SNDL", "NNDM",
]

UNIVERSE_SECTOR_ETFS = [
    "SPY", "QQQ", "XLK", "XLF", "XLE", "XLV", "XLU", "XLC", "XLI",
    "XOP", "GDX", "SOXL", "LABU", "VNQ",
]

FULL_UNIVERSE = UNIVERSE_LARGE_CAP + UNIVERSE_MID_CAP + UNIVERSE_PENNY_HIGH_VOL + UNIVERSE_SECTOR_ETFS


# ─────────────────────────────────────────────────────────────────────────────
# TECHNICAL INDICATOR COMPUTATIONS
# ─────────────────────────────────────────────────────────────────────────────

def compute_rsi(closes: np.ndarray, period: int = 14) -> float:
    """Compute RSI (Relative Strength Index)."""
    if len(closes) < period + 1:
        return 50.0
    deltas = np.diff(closes)
    gains = np.where(deltas > 0, deltas, 0.0)
    losses = np.where(deltas < 0, -deltas, 0.0)
    avg_gain = np.mean(gains[-period:])
    avg_loss = np.mean(losses[-period:])
    if avg_loss == 0:
        return 100.0
    rs = avg_gain / avg_loss
    return round(100.0 - (100.0 / (1.0 + rs)), 2)


def compute_sma(closes: np.ndarray, period: int) -> Optional[float]:
    """Compute Simple Moving Average."""
    if len(closes) < period:
        return None
    return round(float(np.mean(closes[-period:])), 4)


def compute_ema(closes: np.ndarray, period: int) -> Optional[float]:
    """Compute Exponential Moving Average."""
    if len(closes) < period:
        return None
    multiplier = 2.0 / (period + 1)
    ema = closes[0]
    for price in closes[1:]:
        ema = (price - ema) * multiplier + ema
    return round(float(ema), 4)


def compute_atr(highs: np.ndarray, lows: np.ndarray, closes: np.ndarray, period: int = 14) -> float:
    """Compute Average True Range."""
    if len(closes) < period + 1:
        return 0.0
    tr_list = []
    for i in range(1, len(closes)):
        tr = max(
            highs[i] - lows[i],
            abs(highs[i] - closes[i - 1]),
            abs(lows[i] - closes[i - 1])
        )
        tr_list.append(tr)
    if len(tr_list) < period:
        return float(np.mean(tr_list)) if tr_list else 0.0
    return round(float(np.mean(tr_list[-period:])), 4)


def compute_bollinger(closes: np.ndarray, period: int = 20, num_std: float = 2.0) -> dict:
    """Compute Bollinger Bands and position."""
    if len(closes) < period:
        return {"upper": None, "middle": None, "lower": None, "position": "unknown", "bandwidth": 0, "squeeze": False}
    window = closes[-period:]
    middle = float(np.mean(window))
    std = float(np.std(window))
    upper = middle + num_std * std
    lower = middle - num_std * std
    current = float(closes[-1])
    bandwidth = (upper - lower) / middle if middle > 0 else 0

    if current >= upper:
        position = "upper"
    elif current <= lower:
        position = "lower"
    else:
        position = "middle"

    # Squeeze: bandwidth is historically low (< 4% of price)
    squeeze = bandwidth < 0.04

    return {
        "upper": round(upper, 4),
        "middle": round(middle, 4),
        "lower": round(lower, 4),
        "position": position,
        "bandwidth": round(bandwidth, 4),
        "squeeze": squeeze,
    }


def compute_macd(closes: np.ndarray) -> dict:
    """Compute MACD line, signal line, histogram."""
    if len(closes) < 26:
        return {"macd": 0, "signal": 0, "histogram": 0, "trend": "neutral"}
    ema12 = compute_ema(closes, 12)
    ema26 = compute_ema(closes, 26)
    if ema12 is None or ema26 is None:
        return {"macd": 0, "signal": 0, "histogram": 0, "trend": "neutral"}
    macd_line = ema12 - ema26
    # Simplified signal: 9-period EMA of last 9 MACD values
    # For simplicity, approximate with the current MACD scaled
    signal_line = macd_line * 0.8  # rough approximation
    histogram = macd_line - signal_line
    trend = "bullish" if histogram > 0 else "bearish" if histogram < 0 else "neutral"
    return {
        "macd": round(macd_line, 4),
        "signal": round(signal_line, 4),
        "histogram": round(histogram, 4),
        "trend": trend,
    }


def compute_volume_profile(volumes: np.ndarray, period: int = 10) -> dict:
    """Compute volume surge and profile."""
    if len(volumes) < period + 1:
        return {"surge": 1.0, "avg": 0, "current": 0, "z_score": 0}
    current = float(volumes[-1])
    avg = float(np.mean(volumes[-(period + 1):-1]))
    std = float(np.std(volumes[-(period + 1):-1]))
    surge = current / avg if avg > 0 else 1.0
    z_score = (current - avg) / std if std > 0 else 0
    return {
        "surge": round(surge, 4),
        "avg": round(avg, 2),
        "current": round(current, 2),
        "z_score": round(z_score, 4),
    }


def compute_vwap(highs: np.ndarray, lows: np.ndarray, closes: np.ndarray, volumes: np.ndarray) -> Optional[float]:
    """Compute Volume Weighted Average Price (last 20 bars)."""
    n = min(20, len(closes))
    if n < 5:
        return None
    typical = (highs[-n:] + lows[-n:] + closes[-n:]) / 3.0
    cum_vol = np.sum(volumes[-n:])
    if cum_vol == 0:
        return None
    return round(float(np.sum(typical * volumes[-n:]) / cum_vol), 4)


def compute_rs_rating(closes: np.ndarray, spy_closes: np.ndarray) -> float:
    """Compute Relative Strength rating vs SPY (0-100)."""
    if len(closes) < 252 or len(spy_closes) < 252:
        # Use what we have
        n = min(len(closes), len(spy_closes), 60)
        if n < 10:
            return 50.0
    else:
        n = 252

    stock_return = (closes[-1] / closes[-n]) - 1.0 if closes[-n] != 0 else 0
    spy_return = (spy_closes[-1] / spy_closes[-n]) - 1.0 if spy_closes[-n] != 0 else 0

    # RS = stock performance relative to market
    rs = stock_return - spy_return
    # Scale to 0-100 (rs of +0.5 = 100, rs of -0.5 = 0)
    rating = 50.0 + rs * 100.0
    return round(max(0.0, min(100.0, rating)), 2)


def check_breakout(closes: np.ndarray, period: int = 20) -> bool:
    """Check if price is at or near N-day high (breakout)."""
    if len(closes) < period:
        return False
    high_n = float(np.max(closes[-period:]))
    current = float(closes[-1])
    return current >= high_n * 0.98  # within 2% of N-day high


# ─────────────────────────────────────────────────────────────────────────────
# DATA FETCHING
# ─────────────────────────────────────────────────────────────────────────────

def fetch_stock_data(symbol: str, period: str = "1y") -> Optional[dict]:
    """Fetch OHLCV data for a symbol using yfinance.

    Returns dict with numpy arrays: opens, highs, lows, closes, volumes
    plus info dict with name, exchange, market cap, etc.
    """
    if yf is None or pd is None:
        return None
    try:
        ticker = yf.Ticker(symbol)
        hist = ticker.history(period=period, auto_adjust=True)
        if hist is None or hist.empty or len(hist) < 5:
            return None

        info = {}
        try:
            fast_info = ticker.fast_info
            info = {
                "name": getattr(fast_info, 'long_name', None) or symbol,
                "exchange": getattr(fast_info, 'exchange', 'UNKNOWN'),
                "market_cap": getattr(fast_info, 'market_cap', None),
                "currency": getattr(fast_info, 'currency', 'USD'),
            }
        except Exception:
            info = {"name": symbol, "exchange": "UNKNOWN", "market_cap": None, "currency": "USD"}

        return {
            "symbol": symbol,
            "opens": hist["Open"].to_numpy(dtype=float),
            "highs": hist["High"].to_numpy(dtype=float),
            "lows": hist["Low"].to_numpy(dtype=float),
            "closes": hist["Close"].to_numpy(dtype=float),
            "volumes": hist["Volume"].to_numpy(dtype=float),
            "dates": hist.index.tolist(),
            "info": info,
        }
    except Exception as e:
        print(f"[FETCH] Error fetching {symbol}: {e}")
        return None


def fetch_spy_closes() -> Optional[np.ndarray]:
    """Fetch SPY close prices for relative strength calculation."""
    data = fetch_stock_data("SPY", period="1y")
    if data:
        return data["closes"]
    return None


# ─────────────────────────────────────────────────────────────────────────────
# FULL INDICATOR SNAPSHOT
# ─────────────────────────────────────────────────────────────────────────────

def compute_all_indicators(data: dict, spy_closes: Optional[np.ndarray] = None) -> dict:
    """Compute all technical indicators for a stock.

    Returns a dict of all indicator values.
    """
    closes = data["closes"]
    highs = data["highs"]
    lows = data["lows"]
    volumes = data["volumes"]

    current_price = float(closes[-1]) if len(closes) > 0 else 0
    prev_close = float(closes[-2]) if len(closes) > 1 else current_price

    rsi = compute_rsi(closes)
    sma_20 = compute_sma(closes, 20)
    sma_50 = compute_sma(closes, 50)
    sma_200 = compute_sma(closes, 200)
    atr = compute_atr(highs, lows, closes)
    bollinger = compute_bollinger(closes)
    macd = compute_macd(closes)
    vol_profile = compute_volume_profile(volumes)
    vwap = compute_vwap(highs, lows, closes, volumes)
    breakout_20 = check_breakout(closes, 20)
    breakout_50 = check_breakout(closes, 50)

    # RS rating vs SPY
    rs_rating = 50.0
    if spy_closes is not None:
        rs_rating = compute_rs_rating(closes, spy_closes)

    # Stage-2 uptrend check (Minervini-style)
    stage2 = False
    if sma_50 and sma_200 and sma_20:
        stage2 = (current_price > sma_50 > sma_200) and (current_price > sma_20)

    # 52-week high proximity
    year_closes = closes[-252:] if len(closes) >= 252 else closes
    high_52w = float(np.max(year_closes))
    pct_from_52w_high = ((current_price / high_52w) - 1.0) * 100 if high_52w > 0 else -100

    # Price change
    change = current_price - prev_close
    change_pct = (change / prev_close * 100) if prev_close > 0 else 0

    return {
        "current_price": round(current_price, 4),
        "prev_close": round(prev_close, 4),
        "change": round(change, 4),
        "change_pct": round(change_pct, 4),
        "rsi_14": rsi,
        "sma_20": sma_20,
        "sma_50": sma_50,
        "sma_200": sma_200,
        "atr_14": atr,
        "bollinger": bollinger,
        "macd": macd,
        "volume": vol_profile,
        "vwap": vwap,
        "breakout_20d": breakout_20,
        "breakout_50d": breakout_50,
        "rs_rating": rs_rating,
        "stage2_uptrend": stage2,
        "high_52w": round(high_52w, 4),
        "pct_from_52w_high": round(pct_from_52w_high, 2),
        "info": data.get("info", {}),
    }


# ─────────────────────────────────────────────────────────────────────────────
# SCORING ENGINE (default static weights — Adaptive Oracle overrides these)
# ─────────────────────────────────────────────────────────────────────────────

DEFAULT_WEIGHTS = {
    "w_momentum": 0.20,
    "w_volume": 0.20,
    "w_trend": 0.15,
    "w_volatility": 0.10,
    "w_catalyst": 0.10,
    "w_sentiment": 0.05,
    "w_sector_str": 0.05,
    "w_risk_reward": 0.10,
    "w_fee_efficiency": 0.05,
}


def score_momentum(indicators: dict) -> tuple[float, str]:
    """Score momentum component (0-100)."""
    rsi = indicators.get("rsi_14", 50)
    change_pct = indicators.get("change_pct", 0)
    score = 0.0
    notes = []

    # RSI sweet spot: 50-70 is healthy upward momentum
    if 55 <= rsi <= 70:
        score += 40
        notes.append(f"RSI {rsi} in bullish zone")
    elif 45 <= rsi < 55:
        score += 25
        notes.append(f"RSI {rsi} neutral-bullish")
    elif 30 <= rsi < 45:
        score += 35  # potential oversold bounce
        notes.append(f"RSI {rsi} oversold bounce potential")
    elif rsi < 30:
        score += 30
        notes.append(f"RSI {rsi} deeply oversold")
    elif rsi > 70:
        score += 15  # overbought risk
        notes.append(f"RSI {rsi} overbought caution")

    # Recent price change
    if change_pct > 2:
        score += 30
        notes.append(f"+{change_pct}% strong move")
    elif change_pct > 0.5:
        score += 20
        notes.append(f"+{change_pct}% positive")
    elif change_pct > -0.5:
        score += 10
    elif change_pct < -3:
        score += 5  # might bounce but risky

    # MACD
    macd_trend = indicators.get("macd", {}).get("trend", "neutral")
    if macd_trend == "bullish":
        score += 30
        notes.append("MACD bullish")
    elif macd_trend == "neutral":
        score += 10

    return min(100.0, score), "; ".join(notes)


def score_volume(indicators: dict) -> tuple[float, str]:
    """Score volume component (0-100)."""
    vol = indicators.get("volume", {})
    surge = vol.get("surge", 1.0)
    z = vol.get("z_score", 0)
    score = 0.0
    notes = []

    if surge >= 3.0:
        score += 60
        notes.append(f"Vol {surge:.1f}x MASSIVE surge")
    elif surge >= 2.0:
        score += 50
        notes.append(f"Vol {surge:.1f}x strong surge")
    elif surge >= 1.5:
        score += 35
        notes.append(f"Vol {surge:.1f}x above avg")
    elif surge >= 1.1:
        score += 20
        notes.append(f"Vol {surge:.1f}x slightly above avg")
    else:
        score += 5
        notes.append(f"Vol {surge:.1f}x below avg")

    # Z-score bonus
    if z >= 2.0:
        score += 40
        notes.append(f"Vol z-score {z:.1f} (2+ sigma)")
    elif z >= 1.0:
        score += 25
        notes.append(f"Vol z-score {z:.1f}")
    elif z >= 0:
        score += 10

    return min(100.0, score), "; ".join(notes)


def score_trend(indicators: dict) -> tuple[float, str]:
    """Score trend alignment component (0-100)."""
    price = indicators.get("current_price", 0)
    sma20 = indicators.get("sma_20")
    sma50 = indicators.get("sma_50")
    sma200 = indicators.get("sma_200")
    stage2 = indicators.get("stage2_uptrend", False)
    rs = indicators.get("rs_rating", 50)
    pct_52w = indicators.get("pct_from_52w_high", -50)
    score = 0.0
    notes = []

    # Stage-2 uptrend (Minervini)
    if stage2:
        score += 35
        notes.append("Stage-2 uptrend confirmed")

    # Price above key SMAs
    above_count = 0
    for sma_name, sma_val in [("SMA20", sma20), ("SMA50", sma50), ("SMA200", sma200)]:
        if sma_val and price > sma_val:
            above_count += 1
    score += above_count * 10
    if above_count == 3:
        notes.append("Above all key SMAs")
    elif above_count >= 1:
        notes.append(f"Above {above_count}/3 SMAs")

    # RS rating
    if rs >= 80:
        score += 25
        notes.append(f"RS {rs:.0f} strong vs market")
    elif rs >= 60:
        score += 15
        notes.append(f"RS {rs:.0f} above avg")
    elif rs >= 40:
        score += 5

    # 52-week high proximity (within 5% = strong)
    if pct_52w >= -2:
        score += 10
        notes.append("Near 52W high")

    return min(100.0, score), "; ".join(notes)


def score_volatility(indicators: dict) -> tuple[float, str]:
    """Score volatility / Bollinger regime (0-100)."""
    boll = indicators.get("bollinger", {})
    atr = indicators.get("atr_14", 0)
    price = indicators.get("current_price", 1)
    score = 0.0
    notes = []

    # Bollinger squeeze (potential breakout imminent)
    if boll.get("squeeze"):
        score += 50
        notes.append("Bollinger squeeze (breakout imminent)")

    # Position relative to bands
    pos = boll.get("position", "middle")
    if pos == "lower":
        score += 30  # potential bounce from lower band
        notes.append("At lower Bollinger band")
    elif pos == "middle":
        score += 20
    elif pos == "upper":
        score += 10
        notes.append("At upper band (momentum or stretch)")

    # ATR as % of price (moderate volatility is good for day trading)
    atr_pct = (atr / price * 100) if price > 0 else 0
    if 1.0 <= atr_pct <= 4.0:
        score += 30
        notes.append(f"ATR {atr_pct:.1f}% ideal for day trades")
    elif 0.5 <= atr_pct < 1.0:
        score += 15
        notes.append(f"ATR {atr_pct:.1f}% low vol")
    elif atr_pct > 4.0:
        score += 20
        notes.append(f"ATR {atr_pct:.1f}% high vol (bigger moves)")

    return min(100.0, score), "; ".join(notes)


def score_catalyst(indicators: dict) -> tuple[float, str]:
    """Score catalyst / breakout pattern (0-100)."""
    breakout_20 = indicators.get("breakout_20d", False)
    breakout_50 = indicators.get("breakout_50d", False)
    boll = indicators.get("bollinger", {})
    vol_surge = indicators.get("volume", {}).get("surge", 1.0)
    score = 0.0
    notes = []

    if breakout_50:
        score += 40
        notes.append("50-day breakout!")
    elif breakout_20:
        score += 30
        notes.append("20-day breakout")

    # Breakout + volume confirmation
    if (breakout_20 or breakout_50) and vol_surge >= 1.5:
        score += 30
        notes.append(f"Breakout + vol confirmation ({vol_surge:.1f}x)")

    # Squeeze about to pop + volume
    if boll.get("squeeze") and vol_surge >= 1.3:
        score += 30
        notes.append("Squeeze + rising volume")

    return min(100.0, score), "; ".join(notes)


def score_risk_reward(indicators: dict, atr: float, price: float, sl_pct: float = 2.5, tp_pct: float = 5.0) -> tuple[float, str]:
    """Score risk/reward quality (0-100)."""
    score = 0.0
    notes = []

    # R:R ratio
    rr = tp_pct / sl_pct if sl_pct > 0 else 0
    if rr >= 3.0:
        score += 50
        notes.append(f"R:R {rr:.1f}:1 excellent")
    elif rr >= 2.0:
        score += 40
        notes.append(f"R:R {rr:.1f}:1 good")
    elif rr >= 1.5:
        score += 25
        notes.append(f"R:R {rr:.1f}:1 acceptable")
    else:
        score += 10
        notes.append(f"R:R {rr:.1f}:1 weak")

    # ATR-based stop makes sense
    atr_sl = atr * 1.5
    atr_sl_pct = (atr_sl / price * 100) if price > 0 else 0
    if 1.0 <= atr_sl_pct <= 4.0:
        score += 30
        notes.append(f"ATR stop {atr_sl_pct:.1f}% reasonable")
    elif atr_sl_pct < 1.0:
        score += 15
        notes.append("Tight ATR stop")
    else:
        score += 10
        notes.append(f"Wide ATR stop {atr_sl_pct:.1f}%")

    # VWAP alignment (price near or above VWAP is bullish)
    vwap = indicators.get("vwap")
    if vwap and price > 0:
        if price >= vwap:
            score += 20
            notes.append("Above VWAP (institutional support)")
        else:
            score += 5

    return min(100.0, score), "; ".join(notes)


def score_fee_efficiency(symbol: str, price: float, db: MiracleCursorDB) -> tuple[float, str]:
    """Score fee efficiency (0-100). CDRs score higher."""
    score = 50.0  # baseline
    notes = []
    cdr = db.get_cdr_for_symbol(symbol)

    if cdr:
        score += 40
        notes.append(f"CDR available: {cdr['cdr_symbol']} (no FX fee)")
    elif symbol in UNIVERSE_SECTOR_ETFS:
        score += 20
        notes.append("ETF (free to buy on Questrade)")

    # Higher-priced stocks have lower fee impact per share
    if price >= 50:
        score += 10
        notes.append("Price > $50 (low fee impact)")
    elif price < 5:
        score -= 10
        notes.append("Low price (fees eat into profit)")

    return min(100.0, max(0.0, score)), "; ".join(notes)


def compute_composite_score(
    indicators: dict,
    symbol: str,
    db: MiracleCursorDB,
    weights: Optional[dict] = None,
    strategy: Optional[dict] = None,
) -> dict:
    """Compute the full composite score for a stock.

    Args:
        indicators: Full indicator snapshot from compute_all_indicators()
        symbol: Stock ticker
        db: Database instance
        weights: Scoring weights dict. If None, uses DEFAULT_WEIGHTS.
        strategy: Strategy dict for SL/TP parameters.

    Returns:
        Dict with total score, rating, breakdown, and trade plan.
    """
    w = weights or DEFAULT_WEIGHTS
    sl_pct = strategy.get("default_stop_loss_pct", 2.5) if strategy else 2.5
    tp_pct = strategy.get("default_take_profit_pct", 5.0) if strategy else 5.0
    price = indicators.get("current_price", 0)
    atr = indicators.get("atr_14", 0)

    # Compute each component
    c_momentum, n_momentum = score_momentum(indicators)
    c_volume, n_volume = score_volume(indicators)
    c_trend, n_trend = score_trend(indicators)
    c_volatility, n_volatility = score_volatility(indicators)
    c_catalyst, n_catalyst = score_catalyst(indicators)
    c_risk_reward, n_rr = score_risk_reward(indicators, atr, price, sl_pct, tp_pct)
    c_fee, n_fee = score_fee_efficiency(symbol, price, db)

    # Sentiment and sector_str are placeholders (no live data source yet)
    c_sentiment = 50.0
    n_sentiment = "Market sentiment proxy (neutral default)"
    c_sector_str = 50.0
    n_sector_str = "Sector strength (neutral default)"

    # Weighted composite
    components = {
        "momentum": (c_momentum, w.get("w_momentum", 0.20)),
        "volume": (c_volume, w.get("w_volume", 0.20)),
        "trend": (c_trend, w.get("w_trend", 0.15)),
        "volatility": (c_volatility, w.get("w_volatility", 0.10)),
        "catalyst": (c_catalyst, w.get("w_catalyst", 0.10)),
        "sentiment": (c_sentiment, w.get("w_sentiment", 0.05)),
        "sector_str": (c_sector_str, w.get("w_sector_str", 0.05)),
        "risk_reward": (c_risk_reward, w.get("w_risk_reward", 0.10)),
        "fee_efficiency": (c_fee, w.get("w_fee_efficiency", 0.05)),
    }

    total_score = sum(score * weight for score, weight in components.values())
    total_score = round(min(100.0, max(0.0, total_score)), 2)

    # Rating
    if total_score >= 80:
        rating = "STRONG_BUY"
    elif total_score >= 65:
        rating = "BUY"
    elif total_score >= 45:
        rating = "HOLD"
    else:
        rating = "SELL"

    # Confidence
    if total_score >= 85:
        confidence = "very_high"
    elif total_score >= 70:
        confidence = "high"
    elif total_score >= 55:
        confidence = "medium"
    else:
        confidence = "low"

    # Calculate trade plan
    entry_price = round(price * 1.005, 4)  # +0.5% slippage
    stop_loss = round(entry_price * (1 - sl_pct / 100), 4)
    tp1 = round(entry_price * (1 + tp_pct / 100), 4)
    tp2 = round(entry_price * (1 + tp_pct * 1.5 / 100), 4)
    tp3 = round(entry_price * (1 + tp_pct * 2.5 / 100), 4)

    # ATR-based alternative stops
    atr_stop = round(entry_price - atr * 1.5, 4) if atr > 0 else stop_loss
    # Use the tighter of the two
    stop_loss = max(stop_loss, atr_stop)

    rr_ratio = round((tp1 - entry_price) / (entry_price - stop_loss), 2) if entry_price > stop_loss else 0

    # Fee calculation
    fee_calc = QuestradeFeeCaclulator()
    cdr = db.get_cdr_for_symbol(symbol)
    uses_cdr = cdr is not None
    shares_estimate = max(1, int(1000 / price)) if price > 0 else 100  # ~$1000 position
    fee_result = fee_calc.calculate_round_trip_cost(
        shares_estimate, entry_price, tp1, "USD", uses_cdr=uses_cdr
    )

    # Build catalyst string
    catalysts = []
    if n_momentum:
        catalysts.append(n_momentum)
    if n_volume:
        catalysts.append(n_volume)
    if n_catalyst:
        catalysts.append(n_catalyst)
    catalyst_str = " | ".join(catalysts[:3])

    return {
        "symbol": symbol,
        "company_name": indicators.get("info", {}).get("name", symbol),
        "exchange": indicators.get("info", {}).get("exchange", "UNKNOWN"),
        "current_price": price,
        "entry_price": entry_price,
        "stop_loss": stop_loss,
        "take_profit_1": tp1,
        "take_profit_2": tp2,
        "take_profit_3": tp3,
        "risk_reward_ratio": rr_ratio,
        "score": total_score,
        "rating": rating,
        "confidence": confidence,
        "is_cdr": 1 if uses_cdr else 0,
        "cdr_symbol": cdr["cdr_symbol"] if cdr else None,
        "uses_cdr_savings": 1 if uses_cdr else 0,
        "commission_cost": fee_result["total_commission"],
        "fx_fee_cost": fee_result["total_fx_fee"],
        "net_profit_target": fee_result["net_pnl"],
        "position_size_pct": 0,  # calculated at portfolio level
        "estimated_risk_usd": round(shares_estimate * (entry_price - stop_loss), 2),
        "estimated_reward_usd": round(shares_estimate * (tp1 - entry_price), 2),
        "rsi_14": indicators.get("rsi_14"),
        "volume_surge": indicators.get("volume", {}).get("surge"),
        "atr_14": atr,
        "sma_20": indicators.get("sma_20"),
        "sma_50": indicators.get("sma_50"),
        "sma_200": indicators.get("sma_200"),
        "macd_signal": indicators.get("macd", {}).get("trend"),
        "bollinger_pos": indicators.get("bollinger", {}).get("position"),
        "vwap": indicators.get("vwap"),
        "catalyst": catalyst_str,
        # Raw component scores (for adaptive learning)
        "_components": {
            "c_momentum": c_momentum,
            "c_volume": c_volume,
            "c_trend": c_trend,
            "c_volatility": c_volatility,
            "c_catalyst": c_catalyst,
            "c_sentiment": c_sentiment,
            "c_sector_str": c_sector_str,
            "c_risk_reward": c_risk_reward,
            "c_fee_efficiency": c_fee,
        },
        "_breakdowns": [
            {"component_name": "momentum", "component_score": c_momentum, "max_score": 100, "weight": w.get("w_momentum", 0.20), "notes": n_momentum},
            {"component_name": "volume", "component_score": c_volume, "max_score": 100, "weight": w.get("w_volume", 0.20), "notes": n_volume},
            {"component_name": "trend", "component_score": c_trend, "max_score": 100, "weight": w.get("w_trend", 0.15), "notes": n_trend},
            {"component_name": "volatility", "component_score": c_volatility, "max_score": 100, "weight": w.get("w_volatility", 0.10), "notes": n_volatility},
            {"component_name": "catalyst", "component_score": c_catalyst, "max_score": 100, "weight": w.get("w_catalyst", 0.10), "notes": n_catalyst},
            {"component_name": "sentiment", "component_score": c_sentiment, "max_score": 100, "weight": w.get("w_sentiment", 0.05), "notes": n_sentiment},
            {"component_name": "sector_str", "component_score": c_sector_str, "max_score": 100, "weight": w.get("w_sector_str", 0.05), "notes": n_sector_str},
            {"component_name": "risk_reward", "component_score": c_risk_reward, "max_score": 100, "weight": w.get("w_risk_reward", 0.10), "notes": n_rr},
            {"component_name": "fee_efficiency", "component_score": c_fee, "max_score": 100, "weight": w.get("w_fee_efficiency", 0.05), "notes": n_fee},
        ],
    }


# ─────────────────────────────────────────────────────────────────────────────
# SCANNING PIPELINE
# ─────────────────────────────────────────────────────────────────────────────

def scan_universe(
    universe: list[str] = None,
    strategy: dict = None,
    weights: dict = None,
    db: MiracleCursorDB = None,
    top_n: int = 10,
    min_score: float = 65.0,
) -> list[dict]:
    """Scan a universe of stocks, score them, and return the top picks.

    Args:
        universe: List of ticker symbols. Defaults to FULL_UNIVERSE.
        strategy: Strategy dict from DB.
        weights: Custom weights. Defaults to DEFAULT_WEIGHTS.
        db: Database instance.
        top_n: Max number of picks to return.
        min_score: Minimum composite score to qualify.

    Returns:
        List of scored stock dicts, sorted by score descending.
    """
    if db is None:
        db = MiracleCursorDB()
    if universe is None:
        universe = FULL_UNIVERSE
    if strategy:
        min_score = strategy.get("min_score", min_score)

    print(f"\n{'='*70}")
    print(f"  DayTraders Miracle_CURSOR - Scanning {len(universe)} stocks")
    print(f"  Strategy: {strategy['strategy_name'] if strategy else 'Default'}")
    print(f"  Min Score: {min_score} | Top N: {top_n}")
    print(f"  Time: {datetime.utcnow().isoformat()}Z")
    print(f"{'='*70}\n")

    # Fetch SPY for relative strength
    print("[SCAN] Fetching SPY for relative strength baseline...")
    spy_closes = fetch_spy_closes()

    results = []
    scan_date = datetime.utcnow().strftime("%Y-%m-%d")

    for i, symbol in enumerate(universe):
        print(f"[SCAN] ({i+1}/{len(universe)}) {symbol}...", end=" ", flush=True)

        data = fetch_stock_data(symbol, period="1y")
        if data is None:
            print("SKIP (no data)")
            continue

        indicators = compute_all_indicators(data, spy_closes)
        scored = compute_composite_score(indicators, symbol, db, weights, strategy)

        # Log scan result
        db.insert_scan_result(
            scan_date, symbol,
            strategy["strategy_name"] if strategy else "Default",
            scored["score"],
            scored["score"] >= min_score,
            json.dumps({"rsi": scored["rsi_14"], "vol": scored.get("volume_surge"), "atr": scored["atr_14"]})
        )

        if scored["score"] >= min_score:
            results.append(scored)
            print(f"PASS  score={scored['score']}  rating={scored['rating']}")
        else:
            print(f"FAIL  score={scored['score']}")

    # Sort by score descending
    results.sort(key=lambda x: x["score"], reverse=True)

    # Return top N
    top_picks = results[:top_n]

    print(f"\n{'='*70}")
    print(f"  SCAN COMPLETE: {len(results)} passed filter, returning top {len(top_picks)}")
    print(f"{'='*70}\n")

    return top_picks


def save_and_store_signals(
    picks: list[dict],
    strategy_id: int,
    db: MiracleCursorDB,
    output_path: str = None,
) -> list[int]:
    """Save scored picks to the database and optionally export JSON.

    Returns list of signal_ids.
    """
    signal_ids = []
    now = datetime.utcnow().isoformat()

    for p in picks:
        signal = {
            "symbol": p["symbol"],
            "company_name": p.get("company_name", ""),
            "exchange": p.get("exchange", ""),
            "is_cdr": p.get("is_cdr", 0),
            "cdr_symbol": p.get("cdr_symbol"),
            "strategy_id": strategy_id,
            "signal_type": "LONG",
            "rating": p["rating"],
            "score": p["score"],
            "current_price": p["current_price"],
            "entry_price": p["entry_price"],
            "stop_loss": p["stop_loss"],
            "take_profit_1": p["take_profit_1"],
            "take_profit_2": p.get("take_profit_2"),
            "take_profit_3": p.get("take_profit_3"),
            "risk_reward_ratio": p.get("risk_reward_ratio", 0),
            "position_size_pct": p.get("position_size_pct", 0),
            "estimated_risk_usd": p.get("estimated_risk_usd", 0),
            "estimated_reward_usd": p.get("estimated_reward_usd", 0),
            "commission_cost": p.get("commission_cost", 0),
            "fx_fee_cost": p.get("fx_fee_cost", 0),
            "net_profit_target": p.get("net_profit_target", 0),
            "uses_cdr_savings": p.get("uses_cdr_savings", 0),
            "rsi_14": p.get("rsi_14"),
            "volume_surge": p.get("volume_surge"),
            "atr_14": p.get("atr_14"),
            "sma_20": p.get("sma_20"),
            "sma_50": p.get("sma_50"),
            "sma_200": p.get("sma_200"),
            "macd_signal": p.get("macd_signal"),
            "bollinger_pos": p.get("bollinger_pos"),
            "vwap": p.get("vwap"),
            "catalyst": p.get("catalyst", ""),
            "confidence": p.get("confidence", "medium"),
            "timeframe": "1d",
            "status": "active",
            "picked_at": now,
        }

        sid = db.insert_signal(signal)
        signal_ids.append(sid)

        # Store breakdowns
        breakdowns = p.get("_breakdowns", [])
        if breakdowns:
            db.insert_score_breakdown(sid, breakdowns)

        print(f"  [DB] Stored signal #{sid}: {p['symbol']} score={p['score']} rating={p['rating']}")

    # Export JSON
    if output_path:
        db.export_signals_json(output_path)

    return signal_ids
