"""
DayTraders Miracle_CURSOR - Questrade Fee Calculator
=====================================================
Generated by: Cursor AI Agent (cursor-generated)
Date: 2026-02-09

Calculates accurate trading costs for Questrade accounts, including:
- Equity commissions ($4.95-$9.95, $0.01/share)
- ECN fees (~$0.0035/share)
- FX conversion fees (1.5% for USD trades)
- CDR (Canadian Depositary Receipt) savings
- ETF buy-free advantage

Reference: https://www.questrade.com/pricing/self-directed-commissions-plans-background
"""


class QuestradeFeeCaclulator:
    """Calculate Questrade trading fees and CDR savings."""
    
    # Commission structure
    MIN_COMMISSION = 4.95       # CAD per trade
    MAX_COMMISSION = 9.95       # CAD per trade
    PER_SHARE_FEE = 0.01        # CAD per share
    ECN_FEE_PER_SHARE = 0.0035  # CAD per share (approximate)
    
    # FX conversion
    FX_SPREAD_PCT = 1.5         # 1.5% on USD/CAD conversion
    
    # ETF
    ETF_BUY_FEE = 0.0           # Free to buy ETFs
    
    def __init__(self, account_currency: str = "CAD"):
        self.account_currency = account_currency.upper()
    
    def calculate_commission(self, shares: int, is_etf_buy: bool = False) -> float:
        """Calculate commission for a trade.
        
        Args:
            shares: Number of shares traded
            is_etf_buy: True if buying an ETF (free on Questrade)
        
        Returns:
            Commission in CAD
        """
        if is_etf_buy:
            return 0.0
        
        raw_commission = shares * self.PER_SHARE_FEE
        return max(self.MIN_COMMISSION, min(raw_commission, self.MAX_COMMISSION))
    
    def calculate_ecn_fee(self, shares: int) -> float:
        """Calculate ECN/routing fee."""
        return shares * self.ECN_FEE_PER_SHARE
    
    def calculate_fx_fee(self, trade_value_usd: float, uses_cdr: bool = False) -> float:
        """Calculate FX conversion fee for USD trades.
        
        If using a CDR on NEO exchange, no FX fee is charged since
        CDRs trade in CAD and are currency-hedged.
        
        Args:
            trade_value_usd: Total trade value in USD
            uses_cdr: True if using CDR (no FX fee)
        
        Returns:
            FX fee in CAD (0 if CDR)
        """
        if uses_cdr or self.account_currency == "USD":
            return 0.0
        return trade_value_usd * (self.FX_SPREAD_PCT / 100.0)
    
    def calculate_round_trip_cost(
        self,
        shares: int,
        entry_price: float,
        exit_price: float,
        stock_currency: str = "USD",
        uses_cdr: bool = False,
        is_etf: bool = False
    ) -> dict:
        """Calculate full round-trip trading cost (buy + sell).
        
        Args:
            shares: Number of shares
            entry_price: Buy price per share
            exit_price: Sell price per share (target)
            stock_currency: Currency the stock trades in
            uses_cdr: Whether using CDR to avoid FX fees
            is_etf: Whether the instrument is an ETF
        
        Returns:
            Dict with cost breakdown
        """
        buy_value = shares * entry_price
        sell_value = shares * exit_price
        
        # Commissions
        buy_commission = self.calculate_commission(shares, is_etf_buy=is_etf)
        sell_commission = self.calculate_commission(shares, is_etf_buy=False)
        total_commission = buy_commission + sell_commission
        
        # ECN fees
        buy_ecn = self.calculate_ecn_fee(shares)
        sell_ecn = self.calculate_ecn_fee(shares)
        total_ecn = buy_ecn + sell_ecn
        
        # FX fees (on both buy and sell for USD stocks in CAD account)
        is_foreign = stock_currency.upper() != self.account_currency
        buy_fx = self.calculate_fx_fee(buy_value, uses_cdr) if is_foreign else 0.0
        sell_fx = self.calculate_fx_fee(sell_value, uses_cdr) if is_foreign else 0.0
        total_fx = buy_fx + sell_fx
        
        # CDR savings
        cdr_savings = 0.0
        if uses_cdr and is_foreign:
            # What you WOULD have paid in FX fees without CDR
            cdr_savings = (buy_value + sell_value) * (self.FX_SPREAD_PCT / 100.0)
        
        # Total costs
        total_cost = total_commission + total_ecn + total_fx
        
        # Gross P&L
        gross_pnl = sell_value - buy_value
        
        # Net P&L
        net_pnl = gross_pnl - total_cost
        
        # Breakeven price
        total_buy_cost = buy_value + buy_commission + buy_ecn + buy_fx
        per_share_cost = total_buy_cost / shares if shares > 0 else 0
        sell_costs_per_share = (sell_commission + sell_ecn) / shares if shares > 0 else 0
        breakeven_price = per_share_cost + sell_costs_per_share
        
        return {
            "shares": shares,
            "entry_price": entry_price,
            "exit_price": exit_price,
            "buy_value": round(buy_value, 2),
            "sell_value": round(sell_value, 2),
            "buy_commission": round(buy_commission, 2),
            "sell_commission": round(sell_commission, 2),
            "total_commission": round(total_commission, 2),
            "total_ecn": round(total_ecn, 2),
            "total_fx_fee": round(total_fx, 2),
            "cdr_savings": round(cdr_savings, 2),
            "uses_cdr": uses_cdr,
            "total_cost": round(total_cost, 2),
            "gross_pnl": round(gross_pnl, 2),
            "net_pnl": round(net_pnl, 2),
            "net_return_pct": round((net_pnl / buy_value) * 100, 4) if buy_value > 0 else 0,
            "breakeven_price": round(breakeven_price, 4),
            "cost_as_pct_of_trade": round((total_cost / buy_value) * 100, 4) if buy_value > 0 else 0,
        }
    
    def min_profitable_move_pct(
        self,
        shares: int,
        entry_price: float,
        stock_currency: str = "USD",
        uses_cdr: bool = False,
        is_etf: bool = False
    ) -> float:
        """Calculate the minimum % price move needed to break even after all fees.
        
        This is critical for day trading - if fees eat too much, the trade isn't viable.
        """
        # Estimate costs at breakeven (sell = buy)
        costs = self.calculate_round_trip_cost(
            shares, entry_price, entry_price,
            stock_currency, uses_cdr, is_etf
        )
        total_cost = costs["total_cost"]
        trade_value = shares * entry_price
        
        return round((total_cost / trade_value) * 100, 4) if trade_value > 0 else 999.0


def demo():
    """Demo the fee calculator."""
    calc = QuestradeFeeCaclulator(account_currency="CAD")
    
    print("=" * 70)
    print("DayTraders Miracle_CURSOR - Questrade Fee Calculator Demo")
    print("=" * 70)
    
    # Example 1: US stock without CDR
    print("\n--- Example 1: Buy 100 shares AAPL @ $200, sell @ $210 (no CDR) ---")
    result = calc.calculate_round_trip_cost(100, 200, 210, "USD", uses_cdr=False)
    for k, v in result.items():
        print(f"  {k}: {v}")
    
    # Example 2: Same trade with CDR
    print("\n--- Example 2: Buy 100 shares AAPL.NE CDR @ $200, sell @ $210 (CDR) ---")
    result = calc.calculate_round_trip_cost(100, 200, 210, "USD", uses_cdr=True)
    for k, v in result.items():
        print(f"  {k}: {v}")
    
    # Example 3: Minimum profitable move
    print("\n--- Minimum move to profit (100 shares @ $50) ---")
    no_cdr = calc.min_profitable_move_pct(100, 50, "USD", uses_cdr=False)
    with_cdr = calc.min_profitable_move_pct(100, 50, "USD", uses_cdr=True)
    print(f"  Without CDR: {no_cdr}%")
    print(f"  With CDR:    {with_cdr}%")
    print(f"  CDR Advantage: {round(no_cdr - with_cdr, 4)}% lower breakeven")


if __name__ == "__main__":
    demo()
