#!/usr/bin/env python3
"""
DayTraders Miracle_CURSOR - Main Runner
=========================================
Generated by: Cursor AI Agent (cursor-generated)
Date: 2026-02-09

Entry point for the DayTraders Miracle_CURSOR tool.
Supports multiple modes:
  - scan          : Scan the full universe and generate today's picks
  - scan-oracle   : Same scan but using Adaptive Oracle's learned weights
  - strategies    : List all available strategies
  - portfolios    : List all portfolios
  - signals       : Show active trading signals
  - learn         : Process closed signals and feed outcomes to the Oracle
  - calibration   : Show Oracle calibration stats
  - summary       : Full learning summary
  - export        : Export signals to JSON (for website integration)
  - demo          : Run a demo with simulated trades
  - demo-oracle   : Run the Adaptive Oracle demo

Usage:
    python run_miracle.py scan
    python run_miracle.py scan --strategy "Miracle Momentum Burst" --top 5
    python run_miracle.py scan-oracle --top 5
    python run_miracle.py learn --signal-id 1
    python run_miracle.py export --output data/miracle-signals.json
    python run_miracle.py summary
    python run_miracle.py demo
"""

import sys
import os
import json
import argparse
from datetime import datetime
from pathlib import Path

# Ensure project root is in path
sys.path.insert(0, str(Path(__file__).parent))

from db.database_1 import MiracleCursorDB
from miracle_engine import (
    scan_universe, save_and_store_signals,
    fetch_stock_data, compute_all_indicators, fetch_spy_closes,
    FULL_UNIVERSE, UNIVERSE_LARGE_CAP, UNIVERSE_MID_CAP,
    UNIVERSE_PENNY_HIGH_VOL, UNIVERSE_SECTOR_ETFS,
)
from strategies.adaptive_oracle_1 import AdaptiveOracle
from questrade_fees import QuestradeFeeCaclulator


BANNER = r"""
╔══════════════════════════════════════════════════════════════════════╗
║                                                                      ║
║   ██████╗  █████╗ ██╗   ██╗████████╗██████╗  █████╗ ██████╗ ███████╗║
║   ██╔══██╗██╔══██╗╚██╗ ██╔╝╚══██╔══╝██╔══██╗██╔══██╗██╔══██╗██╔════╝║
║   ██║  ██║███████║ ╚████╔╝    ██║   ██████╔╝███████║██║  ██║█████╗  ║
║   ██║  ██║██╔══██║  ╚██╔╝     ██║   ██╔══██╗██╔══██║██║  ██║██╔══╝  ║
║   ██████╔╝██║  ██║   ██║      ██║   ██║  ██║██║  ██║██████╔╝███████╗║
║   ╚═════╝ ╚═╝  ╚═╝   ╚═╝      ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝ ╚══════╝║
║                                                                      ║
║           M I R A C L E _ C U R S O R   T O O L                     ║
║           Generated by Cursor AI Agent                               ║
║           Part of the STOCKSUNIFY2 Ecosystem                         ║
║                                                                      ║
╚══════════════════════════════════════════════════════════════════════╝
"""


def print_banner():
    print(BANNER)
    print(f"  Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} UTC")
    print()


def cmd_scan(args, db):
    """Run a full universe scan with a static strategy."""
    strategy = None
    if args.strategy:
        strategy = db.get_strategy_by_name(args.strategy)
        if not strategy:
            print(f"[ERROR] Strategy '{args.strategy}' not found.")
            print("Available strategies:")
            for s in db.get_strategies():
                print(f"  - {s['strategy_name']}")
            return

    universe = FULL_UNIVERSE
    if args.universe == "large":
        universe = UNIVERSE_LARGE_CAP
    elif args.universe == "mid":
        universe = UNIVERSE_MID_CAP
    elif args.universe == "penny":
        universe = UNIVERSE_PENNY_HIGH_VOL
    elif args.universe == "etf":
        universe = UNIVERSE_SECTOR_ETFS

    picks = scan_universe(
        universe=universe,
        strategy=strategy,
        db=db,
        top_n=args.top,
        min_score=args.min_score or (strategy["min_score"] if strategy else 65.0),
    )

    if picks:
        strategy_id = strategy["strategy_id"] if strategy else 1
        output_path = args.output or "data/miracle-signals.json"
        signal_ids = save_and_store_signals(picks, strategy_id, db, output_path)
        _print_picks_table(picks)
        print(f"\n  Saved {len(signal_ids)} signals to database and {output_path}")
    else:
        print("\n  No picks met the minimum score threshold.")


def cmd_scan_oracle(args, db):
    """Run a scan using the Adaptive Oracle's learned weights."""
    oracle = AdaptiveOracle(db)

    # Get Oracle strategy
    strategy = db.get_strategy_by_name("Adaptive Oracle")
    if not strategy:
        print("[ERROR] Adaptive Oracle strategy not found in database.")
        return

    strategy_id = strategy["strategy_id"]

    # Get learned weights
    weights_row = oracle.get_current_weights(strategy_id)
    weights = {k: weights_row.get(k, 0.1) for k in [
        "w_momentum", "w_volume", "w_trend", "w_volatility", "w_catalyst",
        "w_sentiment", "w_sector_str", "w_risk_reward", "w_fee_efficiency",
    ]}

    epoch = weights_row.get("epoch", 0)
    confidence = weights_row.get("confidence", 0.5)

    print(f"\n[ORACLE] Using Adaptive Oracle weights (Epoch {epoch}, Confidence {confidence:.2f})")
    for k, v in weights.items():
        print(f"  {k}: {v:.4f}")

    # Filter universe (remove blacklisted)
    universe = oracle.filter_universe(FULL_UNIVERSE)

    picks = scan_universe(
        universe=universe,
        strategy=strategy,
        weights=weights,
        db=db,
        top_n=args.top,
        min_score=args.min_score or strategy["min_score"],
    )

    if picks:
        output_path = args.output or "data/oracle-signals.json"
        signal_ids = save_and_store_signals(picks, strategy_id, db, output_path)
        _print_picks_table(picks)
        print(f"\n  Saved {len(signal_ids)} Oracle signals to database and {output_path}")
    else:
        print("\n  No picks met the Oracle's threshold.")


def cmd_strategies(args, db):
    """List all strategies."""
    strategies = db.get_strategies(active_only=not args.all)
    print(f"\n{'Strategy Name':<30} {'Type':<18} {'Risk':<12} {'TF':<6} {'Min Score':<10} {'SL%':<6} {'TP%':<6} {'CDR':<5}")
    print("-" * 110)
    for s in strategies:
        print(f"{s['strategy_name']:<30} {s['strategy_type']:<18} {s['risk_level']:<12} {s['timeframe']:<6} {s['min_score']:<10} {s['default_stop_loss_pct']:<6} {s['default_take_profit_pct']:<6} {'Y' if s['prefer_cdr'] else 'N':<5}")


def cmd_portfolios(args, db):
    """List all portfolios."""
    portfolios = db.get_portfolios(active_only=not args.all)
    print(f"\n{'Portfolio Name':<25} {'Capital':<12} {'Currency':<8} {'Risk/Trade':<12} {'Broker':<12} {'Account':<8}")
    print("-" * 85)
    for p in portfolios:
        print(f"{p['portfolio_name']:<25} ${p['current_capital']:>10,.2f} {p['currency']:<8} {p['max_risk_per_trade_pct']}%{'':<8} {p['broker']:<12} {p['account_type']:<8}")


def cmd_signals(args, db):
    """Show active trading signals."""
    signals = db.get_active_signals()
    if not signals:
        print("\n  No active signals.")
        return
    _print_picks_table_from_signals(signals)


def cmd_learn(args, db):
    """Feed a closed signal's outcome to the Oracle."""
    oracle = AdaptiveOracle(db)
    if args.signal_id:
        result = oracle.learn_from_outcome(args.signal_id, args.strategy_id or 7)
        print(json.dumps(result, indent=2, default=str))
    elif args.learn_all:
        # Learn from all closed signals that haven't been processed
        conn = db._connect()
        closed = conn.execute(
            """SELECT signal_id, strategy_id FROM trading_signals_1
               WHERE status = 'closed'
               AND signal_id NOT IN (SELECT signal_id FROM feedback_loop_1)"""
        ).fetchall()
        conn.close()

        if not closed:
            print("  No unprocessed closed signals found.")
            return

        print(f"  Processing {len(closed)} closed signals...")
        for row in closed:
            result = oracle.learn_from_outcome(row["signal_id"], row["strategy_id"])
            print(f"  Learned from signal #{row['signal_id']}: {result.get('outcome', '?')}")
    else:
        print("  Specify --signal-id N or --learn-all")


def cmd_calibration(args, db):
    """Show Oracle calibration stats."""
    oracle = AdaptiveOracle(db)
    stats = oracle.get_calibration_stats()
    if not stats:
        print("  No calibration data yet. Run some trades first!")
        return
    print("\n  Oracle Prediction Calibration:")
    print(f"  {'Bucket':<20} {'Total':<8} {'Correct':<10} {'Accuracy':<10} {'Avg Move':<12} {'Avg Error':<10}")
    print("  " + "-" * 70)
    for bucket, s in stats.items():
        print(f"  {bucket:<20} {s['total']:<8} {s['correct']:<10} {s['accuracy']}%{'':<6} {s['avg_magnitude']:<12} {s['avg_error']:<10}")


def cmd_summary(args, db):
    """Full Oracle learning summary."""
    oracle = AdaptiveOracle(db)
    strategy = db.get_strategy_by_name("Adaptive Oracle")
    strategy_id = strategy["strategy_id"] if strategy else 7
    summary = oracle.get_learning_summary(strategy_id)
    print(json.dumps(summary, indent=2, default=str))


def cmd_export(args, db):
    """Export signals to JSON."""
    output_path = args.output or "data/miracle-signals.json"
    db.export_signals_json(output_path)
    print(f"  Exported to {output_path}")


def cmd_demo(args, db):
    """Run a quick demo scan on a small set of tickers."""
    demo_tickers = ["AAPL", "MSFT", "NVDA", "TSLA", "GOOGL", "META", "AMD", "INTC", "SPY", "QQQ"]
    print(f"\n[DEMO] Scanning {len(demo_tickers)} popular tickers...")

    strategy = db.get_strategy_by_name("Miracle Momentum Burst") or db.get_strategy(1)
    picks = scan_universe(
        universe=demo_tickers,
        strategy=strategy,
        db=db,
        top_n=5,
        min_score=50.0,  # Lower threshold for demo
    )

    if picks:
        _print_picks_table(picks)
        output = "data/demo-signals.json"
        save_and_store_signals(picks, strategy["strategy_id"] if strategy else 1, db, output)
        print(f"\n  Demo picks saved to {output}")
    else:
        print("\n  No picks in demo (market may be closed or data unavailable).")


def cmd_demo_oracle(args, db):
    """Run the Adaptive Oracle demo with simulated trades."""
    from strategies.adaptive_oracle_1 import demo_adaptive_oracle
    demo_adaptive_oracle()


def cmd_fees(args, db):
    """Show Questrade fee comparison (CDR vs non-CDR)."""
    calc = QuestradeFeeCaclulator(account_currency="CAD")
    print("\n  Questrade Fee Comparison: CDR vs Direct US Stock Purchase")
    print("  " + "=" * 65)

    test_cases = [
        ("AAPL", 100, 200.0, 210.0),
        ("NVDA", 10, 800.0, 840.0),
        ("INTC", 200, 50.0, 52.5),
        ("META", 30, 600.0, 630.0),
    ]

    for symbol, shares, entry, exit_p in test_cases:
        cdr = db.get_cdr_for_symbol(symbol)
        no_cdr = calc.calculate_round_trip_cost(shares, entry, exit_p, "USD", uses_cdr=False)
        with_cdr = calc.calculate_round_trip_cost(shares, entry, exit_p, "USD", uses_cdr=True)

        print(f"\n  {symbol} ({shares} shares @ ${entry} -> ${exit_p}):")
        print(f"    Direct US:  Cost ${no_cdr['total_cost']:>8.2f}  |  Net P&L ${no_cdr['net_pnl']:>8.2f}  ({no_cdr['net_return_pct']:+.2f}%)")
        if cdr:
            print(f"    CDR ({cdr['cdr_symbol']}): Cost ${with_cdr['total_cost']:>8.2f}  |  Net P&L ${with_cdr['net_pnl']:>8.2f}  ({with_cdr['net_return_pct']:+.2f}%)")
            print(f"    CDR Savings: ${no_cdr['total_cost'] - with_cdr['total_cost']:.2f}")
        else:
            print(f"    No CDR available for {symbol}")


def _print_picks_table(picks):
    """Pretty-print picks as a table."""
    print(f"\n  {'#':<3} {'Symbol':<8} {'Score':<7} {'Rating':<12} {'Price':<10} {'Entry':<10} {'SL':<10} {'TP1':<10} {'R:R':<6} {'CDR':<6} {'Catalyst':<40}")
    print("  " + "-" * 130)
    for i, p in enumerate(picks, 1):
        cdr_flag = "CDR" if p.get("is_cdr") or p.get("uses_cdr_savings") else ""
        catalyst = (p.get("catalyst", "")[:38] + "..") if len(p.get("catalyst", "")) > 40 else p.get("catalyst", "")
        print(f"  {i:<3} {p['symbol']:<8} {p['score']:<7.1f} {p['rating']:<12} ${p['current_price']:<9.2f} ${p['entry_price']:<9.2f} ${p['stop_loss']:<9.2f} ${p['take_profit_1']:<9.2f} {p.get('risk_reward_ratio', 0):<6.1f} {cdr_flag:<6} {catalyst:<40}")


def _print_picks_table_from_signals(signals):
    """Pretty-print database signals as a table."""
    print(f"\n  {'ID':<5} {'Symbol':<8} {'Score':<7} {'Rating':<12} {'Price':<10} {'Entry':<10} {'SL':<10} {'TP1':<10} {'Status':<10}")
    print("  " + "-" * 90)
    for s in signals:
        print(f"  {s['signal_id']:<5} {s['symbol']:<8} {s['score']:<7.1f} {s['rating']:<12} ${s['current_price']:<9.2f} ${s['entry_price']:<9.2f} ${s['stop_loss']:<9.2f} ${s['take_profit_1']:<9.2f} {s['status']:<10}")


def main():
    print_banner()

    parser = argparse.ArgumentParser(
        description="DayTraders Miracle_CURSOR - AI-powered stock scanning tool (cursor-generated)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    sub = parser.add_subparsers(dest="command")

    # scan
    p_scan = sub.add_parser("scan", help="Scan universe and generate picks")
    p_scan.add_argument("--strategy", type=str, default=None, help="Strategy name")
    p_scan.add_argument("--universe", choices=["full", "large", "mid", "penny", "etf"], default="full")
    p_scan.add_argument("--top", type=int, default=10, help="Max picks to return")
    p_scan.add_argument("--min-score", type=float, default=None, help="Min composite score")
    p_scan.add_argument("--output", type=str, default=None, help="Output JSON path")

    # scan-oracle
    p_oracle_scan = sub.add_parser("scan-oracle", help="Scan with Adaptive Oracle weights")
    p_oracle_scan.add_argument("--top", type=int, default=10)
    p_oracle_scan.add_argument("--min-score", type=float, default=None)
    p_oracle_scan.add_argument("--output", type=str, default=None)

    # strategies
    p_strat = sub.add_parser("strategies", help="List strategies")
    p_strat.add_argument("--all", action="store_true", help="Include inactive")

    # portfolios
    p_port = sub.add_parser("portfolios", help="List portfolios")
    p_port.add_argument("--all", action="store_true")

    # signals
    sub.add_parser("signals", help="Show active signals")

    # learn
    p_learn = sub.add_parser("learn", help="Feed outcomes to Oracle")
    p_learn.add_argument("--signal-id", type=int, default=None)
    p_learn.add_argument("--strategy-id", type=int, default=None)
    p_learn.add_argument("--learn-all", action="store_true")

    # calibration
    sub.add_parser("calibration", help="Oracle calibration stats")

    # summary
    sub.add_parser("summary", help="Full Oracle learning summary")

    # export
    p_export = sub.add_parser("export", help="Export signals to JSON")
    p_export.add_argument("--output", type=str, default=None)

    # demo
    sub.add_parser("demo", help="Quick demo scan")

    # demo-oracle
    sub.add_parser("demo-oracle", help="Adaptive Oracle demo with simulated trades")

    # fees
    sub.add_parser("fees", help="Questrade CDR fee comparison")

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        return

    # Initialize database
    db = MiracleCursorDB()

    commands = {
        "scan": cmd_scan,
        "scan-oracle": cmd_scan_oracle,
        "strategies": cmd_strategies,
        "portfolios": cmd_portfolios,
        "signals": cmd_signals,
        "learn": cmd_learn,
        "calibration": cmd_calibration,
        "summary": cmd_summary,
        "export": cmd_export,
        "demo": cmd_demo,
        "demo-oracle": cmd_demo_oracle,
        "fees": cmd_fees,
    }

    cmd_func = commands.get(args.command)
    if cmd_func:
        cmd_func(args, db)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
