"""
DayTraders Miracle_CURSOR - Adaptive Oracle (Self-Adjusting Algorithm)
======================================================================
Generated by: Cursor AI Agent (cursor-generated)
Date: 2026-02-09

THE SISTER ALGORITHM:
This is a self-adjusting scoring algorithm that *learns from its own failures*
and improves accuracy day by day. It works alongside the static Miracle engine
but continuously evolves.

HOW IT LEARNS:
1. After every trade outcome (win/loss), it examines WHICH scoring components
   contributed most to the pick.
2. If the pick was a LOSS, it reduces the weight of components that scored
   highest (they "lied" about the opportunity).
3. If the pick was a WIN, it increases the weight of components that scored
   highest (they correctly identified the opportunity).
4. Weight adjustments are proportional to: (a) the magnitude of the P&L,
   (b) the component's contribution to the overall score, and (c) a
   decaying learning rate so older lessons fade gracefully.
5. Over time, the Oracle gravitates toward the indicator mix that actually
   predicts profitability for its specific universe and timeframe.

ADDITIONAL INTELLIGENCE:
- Per-symbol memory: avoids tickers where it consistently fails
- Market regime awareness: adjusts more cautiously in volatile regimes
- Confidence calibration: tracks whether "high confidence" picks actually win
  more often, and recalibrates if not
- Epoch-based snapshots: stores weight history so you can diff or rollback

This is NOT a black-box ML model. Every adjustment is logged, auditable,
and explainable.
"""

import json
import math
from datetime import datetime
from typing import Optional

from db.database_1 import MiracleCursorDB

# Component names matching the weight columns in adaptive_weights_1
COMPONENT_NAMES = [
    "momentum", "volume", "trend", "volatility", "catalyst",
    "sentiment", "sector_str", "risk_reward", "fee_efficiency",
]

WEIGHT_COLUMNS = [f"w_{c}" for c in COMPONENT_NAMES]
COMPONENT_COLUMNS = [f"c_{c}" for c in COMPONENT_NAMES]
DELTA_COLUMNS = [f"delta_{c}" for c in COMPONENT_NAMES]


class AdaptiveOracle:
    """
    Self-adjusting scoring algorithm that learns from trade outcomes.

    Usage:
        oracle = AdaptiveOracle(db)
        weights = oracle.get_current_weights(strategy_id)
        # ... use weights in the scoring engine ...
        # After a trade closes:
        oracle.learn_from_outcome(signal_id, strategy_id)
    """

    # Bounds to prevent any single weight from dominating or vanishing
    WEIGHT_MIN = 0.02
    WEIGHT_MAX = 0.40

    # Minimum trades before we start aggressive learning
    MIN_TRADES_FOR_LEARNING = 3

    # Confidence thresholds for calibration
    CONFIDENCE_BUCKETS = {
        "very_high": 85,
        "high": 70,
        "medium": 55,
        "low": 0,
    }

    def __init__(self, db: MiracleCursorDB = None):
        self.db = db or MiracleCursorDB()

    # ─────────────────────────────────────────────────────────────────────
    # WEIGHT MANAGEMENT
    # ─────────────────────────────────────────────────────────────────────

    def get_current_weights(self, strategy_id: int) -> dict:
        """Get the current active weight vector for a strategy.

        Returns dict with keys like 'w_momentum', 'w_volume', etc.
        If no weights exist yet, returns defaults and creates an initial row.
        """
        conn = self.db._connect()
        row = conn.execute(
            "SELECT * FROM adaptive_weights_1 WHERE strategy_id = ? AND is_active = 1 ORDER BY epoch DESC LIMIT 1",
            (strategy_id,)
        ).fetchone()
        conn.close()

        if row:
            return dict(row)

        # No weights yet — create defaults
        return self._create_default_weights(strategy_id)

    def _create_default_weights(self, strategy_id: int) -> dict:
        """Insert default weight vector and return it."""
        conn = self.db._connect()
        conn.execute(
            """INSERT INTO adaptive_weights_1
               (strategy_id, epoch, w_momentum, w_volume, w_trend, w_volatility,
                w_catalyst, w_sentiment, w_sector_str, w_risk_reward, w_fee_efficiency,
                learning_rate, decay_factor, confidence, is_active)
               VALUES (?, 0, 0.20, 0.20, 0.15, 0.10, 0.10, 0.05, 0.05, 0.10, 0.05, 0.05, 0.95, 0.5, 1)""",
            (strategy_id,)
        )
        conn.commit()
        row = conn.execute(
            "SELECT * FROM adaptive_weights_1 WHERE strategy_id = ? AND is_active = 1 ORDER BY epoch DESC LIMIT 1",
            (strategy_id,)
        ).fetchone()
        conn.close()
        return dict(row)

    def _normalize_weights(self, weights: dict) -> dict:
        """Normalize weight vector so it sums to 1.0, respecting min/max bounds."""
        w_keys = WEIGHT_COLUMNS
        raw = {k: max(self.WEIGHT_MIN, min(self.WEIGHT_MAX, weights.get(k, 0.1))) for k in w_keys}
        total = sum(raw.values())
        if total == 0:
            total = 1.0
        normalized = {k: round(v / total, 6) for k, v in raw.items()}
        return normalized

    # ─────────────────────────────────────────────────────────────────────
    # LEARNING FROM OUTCOMES
    # ─────────────────────────────────────────────────────────────────────

    def learn_from_outcome(
        self,
        signal_id: int,
        strategy_id: int,
        market_regime: str = "unknown",
        spy_change_pct: float = 0.0,
        vix_level: float = 0.0,
    ) -> dict:
        """Process a closed trade and adjust weights based on outcome.

        This is the core learning function. Call it every time a signal
        is closed (TP hit, SL hit, expired, or manual close).

        Args:
            signal_id: The closed signal's ID
            strategy_id: The strategy that generated it
            market_regime: 'bull', 'bear', 'sideways', 'volatile'
            spy_change_pct: S&P 500 change during the hold period
            vix_level: VIX level at entry

        Returns:
            Dict describing the adjustment made.
        """
        # 1. Fetch the signal
        conn = self.db._connect()
        signal = conn.execute(
            "SELECT * FROM trading_signals_1 WHERE signal_id = ?", (signal_id,)
        ).fetchone()
        if not signal:
            conn.close()
            return {"error": f"Signal {signal_id} not found"}
        signal = dict(signal)

        # Must be closed
        if signal.get("status") != "closed":
            conn.close()
            return {"error": f"Signal {signal_id} is not closed (status: {signal.get('status')})"}

        # 2. Fetch the score breakdowns
        breakdowns = conn.execute(
            "SELECT * FROM signal_scores_breakdown_1 WHERE signal_id = ?", (signal_id,)
        ).fetchall()
        breakdowns = [dict(b) for b in breakdowns]
        conn.close()

        # Build component score map
        component_scores = {}
        for b in breakdowns:
            name = b["component_name"]
            component_scores[name] = b["component_score"]

        # Fill in any missing components with 50 (neutral)
        for c in COMPONENT_NAMES:
            if c not in component_scores:
                component_scores[c] = 50.0

        # 3. Determine outcome
        entry = signal["entry_price"]
        exit_price = signal.get("actual_exit", entry)
        pnl = signal.get("actual_pnl", 0)
        pnl_pct = (pnl / entry * 100) if entry > 0 else 0

        if pnl > 0:
            outcome = "win"
        elif pnl < 0:
            outcome = "loss"
        else:
            outcome = "breakeven"

        # Hold duration
        picked_at = signal.get("picked_at", "")
        closed_at = signal.get("closed_at", "")
        hold_hours = 0.0
        try:
            dt_pick = datetime.fromisoformat(picked_at.replace("Z", ""))
            dt_close = datetime.fromisoformat(closed_at.replace("Z", ""))
            hold_hours = (dt_close - dt_pick).total_seconds() / 3600.0
        except Exception:
            pass

        # 4. Get current weights
        current_weights = self.get_current_weights(strategy_id)
        epoch = current_weights.get("epoch", 0)
        lr = current_weights.get("learning_rate", 0.05)
        decay = current_weights.get("decay_factor", 0.95)
        total_trades = current_weights.get("total_trades_seen", 0)
        total_wins = current_weights.get("total_wins", 0)
        total_losses = current_weights.get("total_losses", 0)

        # 5. COMPUTE WEIGHT ADJUSTMENTS (the learning step)
        deltas = self._compute_deltas(
            component_scores=component_scores,
            outcome=outcome,
            pnl_pct=pnl_pct,
            learning_rate=lr,
            current_weights=current_weights,
            market_regime=market_regime,
        )

        # 6. Apply deltas to create new weights
        new_weights = {}
        for c in COMPONENT_NAMES:
            w_key = f"w_{c}"
            old_val = current_weights.get(w_key, 0.1)
            delta = deltas.get(c, 0.0)
            new_weights[w_key] = old_val + delta

        new_weights = self._normalize_weights(new_weights)

        # 7. Update stats
        new_epoch = epoch + 1
        total_trades += 1
        if outcome == "win":
            total_wins += 1
        elif outcome == "loss":
            total_losses += 1
        win_rate = (total_wins / total_trades * 100) if total_trades > 0 else 0
        avg_pnl = current_weights.get("avg_pnl", 0)
        avg_pnl = (avg_pnl * (total_trades - 1) + pnl_pct) / total_trades if total_trades > 0 else pnl_pct

        # Decay the learning rate slightly over time (slower learning as it matures)
        new_lr = max(0.005, lr * decay)

        # Confidence: moves toward 1.0 as win rate improves, down toward 0 if losing
        confidence = min(1.0, max(0.0, win_rate / 100.0))
        if total_trades < self.MIN_TRADES_FOR_LEARNING:
            confidence = 0.5  # not enough data

        # 8. Deactivate old weights, insert new snapshot
        conn = self.db._connect()
        conn.execute(
            "UPDATE adaptive_weights_1 SET is_active = 0 WHERE strategy_id = ? AND is_active = 1",
            (strategy_id,)
        )

        weight_vals = [new_weights.get(f"w_{c}", 0.1) for c in COMPONENT_NAMES]
        conn.execute(
            """INSERT INTO adaptive_weights_1
               (strategy_id, epoch, w_momentum, w_volume, w_trend, w_volatility,
                w_catalyst, w_sentiment, w_sector_str, w_risk_reward, w_fee_efficiency,
                learning_rate, decay_factor, confidence,
                total_trades_seen, total_wins, total_losses, win_rate, avg_pnl,
                is_active, notes)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, ?)""",
            (strategy_id, new_epoch, *weight_vals,
             new_lr, decay, round(confidence, 4),
             total_trades, total_wins, total_losses, round(win_rate, 2), round(avg_pnl, 4),
             f"Learned from signal #{signal_id} ({outcome}, PnL {pnl_pct:+.2f}%)")
        )

        # 9. Record in feedback_loop_1
        delta_vals = [round(deltas.get(c, 0.0), 6) for c in COMPONENT_NAMES]
        c_vals = [component_scores.get(c, 50.0) for c in COMPONENT_NAMES]
        conn.execute(
            """INSERT INTO feedback_loop_1
               (signal_id, strategy_id, symbol, outcome, entry_price, exit_price,
                pnl, pnl_pct, hold_duration_hours, exit_reason, original_score,
                c_momentum, c_volume, c_trend, c_volatility, c_catalyst,
                c_sentiment, c_sector_str, c_risk_reward, c_fee_efficiency,
                delta_momentum, delta_volume, delta_trend, delta_volatility, delta_catalyst,
                delta_sentiment, delta_sector_str, delta_risk_reward, delta_fee_efficiency,
                epoch_before, epoch_after, market_regime, spy_change_pct, vix_level)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (signal_id, strategy_id, signal["symbol"],
             outcome, entry, exit_price, pnl, round(pnl_pct, 4),
             round(hold_hours, 2), signal.get("exit_reason", ""),
             signal.get("score", 0),
             *c_vals, *delta_vals,
             epoch, new_epoch, market_regime, spy_change_pct, vix_level)
        )

        conn.commit()
        conn.close()

        # 10. Update symbol memory
        self._update_symbol_memory(signal["symbol"], outcome, pnl_pct, hold_hours, strategy_id)

        # 11. Record oracle prediction calibration
        self._record_prediction_calibration(signal, outcome, pnl_pct)

        result = {
            "signal_id": signal_id,
            "symbol": signal["symbol"],
            "outcome": outcome,
            "pnl_pct": round(pnl_pct, 4),
            "epoch": f"{epoch} -> {new_epoch}",
            "win_rate": f"{win_rate:.1f}%",
            "confidence": round(confidence, 4),
            "learning_rate": round(new_lr, 6),
            "weight_changes": {c: round(deltas.get(c, 0), 6) for c in COMPONENT_NAMES},
            "new_weights": new_weights,
        }

        print(f"\n[ORACLE] Learned from signal #{signal_id} ({signal['symbol']})")
        print(f"  Outcome: {outcome} | PnL: {pnl_pct:+.2f}%")
        print(f"  Epoch: {epoch} -> {new_epoch} | Win Rate: {win_rate:.1f}%")
        print(f"  Top weight change: {max(deltas.items(), key=lambda x: abs(x[1]))}")

        return result

    def _compute_deltas(
        self,
        component_scores: dict,
        outcome: str,
        pnl_pct: float,
        learning_rate: float,
        current_weights: dict,
        market_regime: str = "unknown",
    ) -> dict:
        """Compute the weight adjustment deltas for each component.

        CORE LEARNING LOGIC:
        - On a WIN:  Increase weights for components that scored HIGHEST
                     (they correctly predicted the move)
        - On a LOSS: Decrease weights for components that scored HIGHEST
                     (they gave a false signal — they "lied")
        - On BREAKEVEN: Tiny adjustments toward the mean

        Magnitude of adjustment is proportional to:
        - |PnL %|  : bigger win/loss = bigger lesson
        - Learning rate : decays over time for stability
        - Component's relative score : high-scoring components get adjusted more

        In VOLATILE regimes, learning rate is halved (less trustworthy data).
        """
        deltas = {}

        # Direction of adjustment
        if outcome == "win":
            direction = 1.0    # reinforce what worked
        elif outcome == "loss":
            direction = -1.0   # penalize what failed
        else:
            direction = 0.0    # breakeven — minimal adjustment

        # Scale by PnL magnitude (capped to prevent extreme jumps)
        magnitude = min(abs(pnl_pct) / 100.0, 0.10)  # cap at 10% influence

        # Regime damping
        regime_factor = 1.0
        if market_regime in ("volatile", "bear"):
            regime_factor = 0.5  # learn more cautiously in bad markets

        # Compute each component's contribution (how much it "voted" for this trade)
        total_score = sum(component_scores.values())
        if total_score == 0:
            total_score = 1.0

        for c in COMPONENT_NAMES:
            c_score = component_scores.get(c, 50.0)
            # Contribution: how much this component influenced the pick
            # High-scoring components get adjusted more
            contribution = (c_score / total_score)

            # The delta
            delta = direction * learning_rate * magnitude * contribution * regime_factor

            # Extra: if a component scored very high (>80) and the trade LOST,
            # give it a stronger penalty (it was confidently wrong)
            if outcome == "loss" and c_score > 80:
                delta *= 1.5

            # Extra: if a component scored low (<30) and the trade WON,
            # give it a bonus (it was undervalued)
            if outcome == "win" and c_score < 30:
                delta *= 1.3

            deltas[c] = round(delta, 8)

        return deltas

    # ─────────────────────────────────────────────────────────────────────
    # SYMBOL MEMORY
    # ─────────────────────────────────────────────────────────────────────

    def _update_symbol_memory(
        self, symbol: str, outcome: str, pnl_pct: float,
        hold_hours: float, strategy_id: int
    ):
        """Update per-symbol memory with this trade outcome."""
        conn = self.db._connect()
        row = conn.execute(
            "SELECT * FROM symbol_memory_1 WHERE symbol = ?", (symbol,)
        ).fetchone()

        now = datetime.utcnow().isoformat()

        if row:
            mem = dict(row)
            picked = mem["times_picked"] + 1
            won = mem["times_won"] + (1 if outcome == "win" else 0)
            lost = mem["times_lost"] + (1 if outcome == "loss" else 0)
            wr = (won / picked * 100) if picked > 0 else 0
            # Running average PnL
            avg_pnl = (mem["avg_pnl_pct"] * mem["times_picked"] + pnl_pct) / picked
            best = max(mem["best_pnl_pct"], pnl_pct)
            worst = min(mem["worst_pnl_pct"], pnl_pct)
            avg_hold = (mem["avg_hold_hours"] * mem["times_picked"] + hold_hours) / picked

            # Reliability score: 50 baseline, +/- based on win rate and PnL
            reliability = 50.0 + (wr - 50) * 0.6 + avg_pnl * 2.0
            reliability = max(0.0, min(100.0, reliability))

            # Auto-blacklist: if >5 picks and win rate < 20%, blacklist
            blacklisted = 0
            bl_reason = None
            if picked >= 5 and wr < 20:
                blacklisted = 1
                bl_reason = f"Win rate {wr:.0f}% over {picked} trades"

            conn.execute(
                """UPDATE symbol_memory_1 SET
                   times_picked=?, times_won=?, times_lost=?, win_rate=?,
                   avg_pnl_pct=?, best_pnl_pct=?, worst_pnl_pct=?, avg_hold_hours=?,
                   reliability_score=?, is_blacklisted=?, blacklist_reason=?,
                   last_picked=?, last_updated=?
                   WHERE symbol=?""",
                (picked, won, lost, round(wr, 2), round(avg_pnl, 4),
                 round(best, 4), round(worst, 4), round(avg_hold, 2),
                 round(reliability, 2), blacklisted, bl_reason, now, now, symbol)
            )
        else:
            # First time seeing this symbol
            won = 1 if outcome == "win" else 0
            lost = 1 if outcome == "loss" else 0
            wr = 100.0 if outcome == "win" else 0.0
            conn.execute(
                """INSERT INTO symbol_memory_1
                   (symbol, times_picked, times_won, times_lost, win_rate,
                    avg_pnl_pct, best_pnl_pct, worst_pnl_pct, avg_hold_hours,
                    best_strategy_id, reliability_score, last_picked, last_updated)
                   VALUES (?, 1, ?, ?, ?, ?, ?, ?, ?, ?, 50.0, ?, ?)""",
                (symbol, won, lost, round(wr, 2),
                 round(pnl_pct, 4), round(pnl_pct, 4), round(pnl_pct, 4),
                 round(hold_hours, 2), strategy_id, now, now)
            )

        conn.commit()
        conn.close()

    def get_symbol_memory(self, symbol: str) -> Optional[dict]:
        """Get the Oracle's memory for a specific symbol."""
        conn = self.db._connect()
        row = conn.execute(
            "SELECT * FROM symbol_memory_1 WHERE symbol = ?", (symbol,)
        ).fetchone()
        conn.close()
        return dict(row) if row else None

    def is_symbol_blacklisted(self, symbol: str) -> bool:
        """Check if the Oracle has blacklisted a symbol."""
        mem = self.get_symbol_memory(symbol)
        return mem is not None and mem.get("is_blacklisted", 0) == 1

    def get_reliable_symbols(self, min_reliability: float = 60.0) -> list[dict]:
        """Get symbols the Oracle considers reliable (good track record)."""
        conn = self.db._connect()
        rows = conn.execute(
            "SELECT * FROM symbol_memory_1 WHERE reliability_score >= ? AND is_blacklisted = 0 ORDER BY reliability_score DESC",
            (min_reliability,)
        ).fetchall()
        conn.close()
        return [dict(r) for r in rows]

    # ─────────────────────────────────────────────────────────────────────
    # PREDICTION CALIBRATION
    # ─────────────────────────────────────────────────────────────────────

    def _record_prediction_calibration(self, signal: dict, outcome: str, pnl_pct: float):
        """Record prediction calibration data for accuracy tracking."""
        conn = self.db._connect()
        confidence = signal.get("confidence", "medium")
        score = signal.get("score", 0)
        was_correct = 1 if outcome == "win" else 0

        # Determine calibration bucket
        if score >= 80 and outcome == "win":
            bucket = "high_conf_win"
        elif score >= 80 and outcome == "loss":
            bucket = "high_conf_loss"
        elif score < 80 and outcome == "win":
            bucket = "low_conf_win"
        else:
            bucket = "low_conf_loss"

        conn.execute(
            """INSERT INTO oracle_predictions_1
               (signal_id, symbol, predicted_direction, predicted_magnitude_pct,
                confidence_score, timeframe, actual_direction, actual_magnitude_pct,
                prediction_error, was_correct, calibration_bucket, resolved_at)
               VALUES (?, ?, 'up', ?, ?, '1d', ?, ?, ?, ?, ?, ?)""",
            (signal.get("signal_id"), signal["symbol"],
             signal.get("take_profit_1", 0) - signal.get("entry_price", 0),
             score,
             "up" if pnl_pct > 0 else "down" if pnl_pct < 0 else "flat",
             round(pnl_pct, 4),
             round(abs(pnl_pct - score / 20), 4),  # rough error metric
             was_correct, bucket,
             datetime.utcnow().isoformat())
        )
        conn.commit()
        conn.close()

    def get_calibration_stats(self) -> dict:
        """Get prediction calibration statistics.

        Returns breakdown of how accurate the Oracle's confidence levels are.
        """
        conn = self.db._connect()
        rows = conn.execute(
            """SELECT calibration_bucket,
                      COUNT(*) as total,
                      SUM(was_correct) as correct,
                      ROUND(AVG(actual_magnitude_pct), 4) as avg_magnitude,
                      ROUND(AVG(prediction_error), 4) as avg_error
               FROM oracle_predictions_1
               WHERE resolved_at IS NOT NULL
               GROUP BY calibration_bucket"""
        ).fetchall()
        conn.close()

        stats = {}
        for r in rows:
            r = dict(r)
            bucket = r["calibration_bucket"]
            stats[bucket] = {
                "total": r["total"],
                "correct": r["correct"],
                "accuracy": round(r["correct"] / r["total"] * 100, 2) if r["total"] > 0 else 0,
                "avg_magnitude": r["avg_magnitude"],
                "avg_error": r["avg_error"],
            }
        return stats

    # ─────────────────────────────────────────────────────────────────────
    # MARKET REGIME
    # ─────────────────────────────────────────────────────────────────────

    def record_market_regime(
        self,
        spy_price: float, spy_sma_200: float, spy_rsi: float,
        vix_level: float, sector_leader: str = "", sector_laggard: str = "",
        breadth_pct: float = 50.0
    ) -> str:
        """Determine and record current market regime.

        Returns regime string: 'bull', 'bear', 'sideways', 'volatile'
        """
        # Determine regime
        regime = "sideways"
        regime_score = 50.0

        if vix_level > 30:
            regime = "volatile"
            regime_score = 20.0
        elif spy_price > spy_sma_200 and spy_rsi > 50:
            regime = "bull"
            regime_score = 80.0
        elif spy_price < spy_sma_200 and spy_rsi < 50:
            regime = "bear"
            regime_score = 20.0
        elif spy_price > spy_sma_200:
            regime = "bull"
            regime_score = 65.0

        conn = self.db._connect()
        conn.execute(
            """INSERT INTO regime_memory_1
               (date, spy_price, spy_sma_200, spy_rsi, vix_level, regime, regime_score,
                sector_leader, sector_laggard, breadth_pct)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (datetime.utcnow().strftime("%Y-%m-%d"),
             spy_price, spy_sma_200, spy_rsi, vix_level,
             regime, regime_score, sector_leader, sector_laggard, breadth_pct)
        )
        conn.commit()
        conn.close()

        return regime

    def get_latest_regime(self) -> Optional[dict]:
        """Get the most recently recorded market regime."""
        conn = self.db._connect()
        row = conn.execute(
            "SELECT * FROM regime_memory_1 ORDER BY date DESC LIMIT 1"
        ).fetchone()
        conn.close()
        return dict(row) if row else None

    # ─────────────────────────────────────────────────────────────────────
    # FILTERED UNIVERSE (Oracle excludes blacklisted symbols)
    # ─────────────────────────────────────────────────────────────────────

    def filter_universe(self, universe: list[str]) -> list[str]:
        """Filter out blacklisted symbols from the scan universe.

        This is how the Oracle learns to AVOID tickers where it consistently fails.
        """
        blacklisted = set()
        conn = self.db._connect()
        rows = conn.execute(
            "SELECT symbol FROM symbol_memory_1 WHERE is_blacklisted = 1"
        ).fetchall()
        conn.close()
        blacklisted = {r["symbol"] for r in rows}

        filtered = [s for s in universe if s not in blacklisted]

        if blacklisted:
            removed = blacklisted.intersection(set(universe))
            if removed:
                print(f"[ORACLE] Filtered out {len(removed)} blacklisted symbols: {', '.join(sorted(removed))}")

        return filtered

    # ─────────────────────────────────────────────────────────────────────
    # WEIGHT HISTORY & ANALYSIS
    # ─────────────────────────────────────────────────────────────────────

    def get_weight_history(self, strategy_id: int, limit: int = 20) -> list[dict]:
        """Get the weight evolution history (most recent first)."""
        conn = self.db._connect()
        rows = conn.execute(
            "SELECT * FROM adaptive_weights_1 WHERE strategy_id = ? ORDER BY epoch DESC LIMIT ?",
            (strategy_id, limit)
        ).fetchall()
        conn.close()
        return [dict(r) for r in rows]

    def get_feedback_history(self, strategy_id: int = None, limit: int = 50) -> list[dict]:
        """Get the feedback loop history."""
        conn = self.db._connect()
        q = "SELECT * FROM feedback_loop_1"
        params = []
        if strategy_id:
            q += " WHERE strategy_id = ?"
            params.append(strategy_id)
        q += " ORDER BY analyzed_at DESC LIMIT ?"
        params.append(limit)
        rows = conn.execute(q, params).fetchall()
        conn.close()
        return [dict(r) for r in rows]

    def get_learning_summary(self, strategy_id: int) -> dict:
        """Get a comprehensive summary of the Oracle's learning state."""
        weights = self.get_current_weights(strategy_id)
        calibration = self.get_calibration_stats()
        regime = self.get_latest_regime()

        conn = self.db._connect()
        # Count feedback entries
        fb_count = conn.execute(
            "SELECT COUNT(*) as cnt FROM feedback_loop_1 WHERE strategy_id = ?",
            (strategy_id,)
        ).fetchone()["cnt"]

        # Count blacklisted symbols
        bl_count = conn.execute(
            "SELECT COUNT(*) as cnt FROM symbol_memory_1 WHERE is_blacklisted = 1"
        ).fetchone()["cnt"]

        # Top 5 most reliable symbols
        reliable = conn.execute(
            "SELECT symbol, reliability_score, win_rate, times_picked FROM symbol_memory_1 WHERE is_blacklisted = 0 AND times_picked >= 2 ORDER BY reliability_score DESC LIMIT 5"
        ).fetchall()
        conn.close()

        return {
            "strategy_id": strategy_id,
            "epoch": weights.get("epoch", 0),
            "total_trades": weights.get("total_trades_seen", 0),
            "wins": weights.get("total_wins", 0),
            "losses": weights.get("total_losses", 0),
            "win_rate": weights.get("win_rate", 0),
            "avg_pnl": weights.get("avg_pnl", 0),
            "confidence": weights.get("confidence", 0.5),
            "learning_rate": weights.get("learning_rate", 0.05),
            "current_weights": {k: weights.get(k) for k in WEIGHT_COLUMNS},
            "feedback_entries": fb_count,
            "blacklisted_symbols": bl_count,
            "calibration": calibration,
            "current_regime": dict(regime) if regime else None,
            "top_reliable_symbols": [dict(r) for r in reliable],
        }

    # ─────────────────────────────────────────────────────────────────────
    # SIMULATE LEARNING (for backtesting / demo)
    # ─────────────────────────────────────────────────────────────────────

    def simulate_trade_and_learn(
        self,
        symbol: str,
        strategy_id: int,
        entry_price: float,
        exit_price: float,
        score: float,
        component_scores: dict,
        exit_reason: str = "tp_hit",
    ) -> dict:
        """Simulate a full trade cycle and learn from it.

        Useful for backtesting: create a signal, close it, and learn in one call.
        """
        # Insert a signal
        pnl = exit_price - entry_price
        now = datetime.utcnow().isoformat()
        signal = {
            "symbol": symbol,
            "company_name": symbol,
            "strategy_id": strategy_id,
            "signal_type": "LONG",
            "rating": "BUY" if score >= 65 else "HOLD",
            "score": score,
            "current_price": entry_price,
            "entry_price": entry_price,
            "stop_loss": entry_price * 0.97,
            "take_profit_1": entry_price * 1.05,
            "risk_reward_ratio": 2.0,
            "position_size_pct": 0,
            "estimated_risk_usd": 0,
            "estimated_reward_usd": 0,
            "commission_cost": 9.90,
            "fx_fee_cost": 0,
            "net_profit_target": pnl,
            "confidence": "high" if score >= 75 else "medium",
            "status": "closed",
            "actual_entry": entry_price,
            "actual_exit": exit_price,
            "actual_pnl": pnl,
            "exit_reason": exit_reason,
            "picked_at": now,
            "closed_at": now,
        }

        sid = self.db.insert_signal(signal)

        # Store breakdowns
        breakdowns = []
        for c in COMPONENT_NAMES:
            breakdowns.append({
                "component_name": c,
                "component_score": component_scores.get(c, 50.0),
                "max_score": 100.0,
                "weight": 1.0,
                "notes": "simulated",
            })
        self.db.insert_score_breakdown(sid, breakdowns)

        # Learn
        return self.learn_from_outcome(sid, strategy_id)


def demo_adaptive_oracle():
    """Demo the Adaptive Oracle with simulated trades."""
    print("=" * 70)
    print("  DayTraders Miracle_CURSOR - Adaptive Oracle Demo")
    print("  (Self-Adjusting Algorithm that Learns from Failures)")
    print("=" * 70)

    db = MiracleCursorDB()
    oracle = AdaptiveOracle(db)

    # Find or use the Adaptive Oracle strategy
    strategy = db.get_strategy_by_name("Adaptive Oracle")
    if not strategy:
        print("[DEMO] Adaptive Oracle strategy not found, using strategy_id=7")
        strategy_id = 7
    else:
        strategy_id = strategy["strategy_id"]

    print(f"\n--- Initial Weights (Epoch 0) ---")
    w = oracle.get_current_weights(strategy_id)
    for k in WEIGHT_COLUMNS:
        print(f"  {k}: {w.get(k, '?')}")

    # Simulate some trades
    print("\n--- Simulating Trades ---")

    # Trade 1: WIN - momentum and volume were strong
    print("\n[Trade 1] NVDA: Momentum + Volume strong -> WIN (+3.2%)")
    oracle.simulate_trade_and_learn(
        "NVDA", strategy_id, 800.0, 825.6, 82.0,
        {"momentum": 90, "volume": 85, "trend": 70, "volatility": 50,
         "catalyst": 80, "sentiment": 50, "sector_str": 60, "risk_reward": 75, "fee_efficiency": 70},
        exit_reason="tp_hit"
    )

    # Trade 2: LOSS - catalyst scored high but was false breakout
    print("\n[Trade 2] SNAP: High catalyst score but false breakout -> LOSS (-2.5%)")
    oracle.simulate_trade_and_learn(
        "SNAP", strategy_id, 15.0, 14.625, 71.0,
        {"momentum": 60, "volume": 70, "trend": 45, "volatility": 80,
         "catalyst": 95, "sentiment": 50, "sector_str": 40, "risk_reward": 60, "fee_efficiency": 50},
        exit_reason="sl_hit"
    )

    # Trade 3: WIN - trend alignment was the key
    print("\n[Trade 3] AAPL: Strong trend alignment -> WIN (+4.1%)")
    oracle.simulate_trade_and_learn(
        "AAPL", strategy_id, 200.0, 208.2, 78.0,
        {"momentum": 65, "volume": 55, "trend": 95, "volatility": 40,
         "catalyst": 50, "sentiment": 60, "sector_str": 70, "risk_reward": 80, "fee_efficiency": 90},
        exit_reason="tp_hit"
    )

    # Trade 4: LOSS - volume was high but it was a dump
    print("\n[Trade 4] MARA: High volume was actually a selloff -> LOSS (-4.8%)")
    oracle.simulate_trade_and_learn(
        "MARA", strategy_id, 20.0, 19.04, 69.0,
        {"momentum": 55, "volume": 95, "trend": 30, "volatility": 90,
         "catalyst": 60, "sentiment": 40, "sector_str": 30, "risk_reward": 45, "fee_efficiency": 40},
        exit_reason="sl_hit"
    )

    # Show evolution
    print("\n--- Weight Evolution ---")
    history = oracle.get_weight_history(strategy_id, limit=5)
    for h in reversed(history):
        epoch = h["epoch"]
        print(f"\nEpoch {epoch} (trades: {h['total_trades_seen']}, WR: {h['win_rate']}%, conf: {h['confidence']})")
        for k in WEIGHT_COLUMNS:
            print(f"  {k}: {h.get(k, '?'):.4f}")

    # Show summary
    print("\n--- Learning Summary ---")
    summary = oracle.get_learning_summary(strategy_id)
    print(json.dumps(summary, indent=2, default=str))

    print("\n[ORACLE] Notice how weights shifted:")
    print("  - 'trend' weight INCREASED (correctly predicted wins)")
    print("  - 'catalyst' weight DECREASED (false breakout on SNAP)")
    print("  - 'volume' weight DECREASED (MARA dump was high volume)")
    print("  - The Oracle is now smarter than it was 4 trades ago!")


if __name__ == "__main__":
    demo_adaptive_oracle()
